SELECT
A.EC,
CONVERT(DATE, A.DATA_BASE, 103) AS DATA_BASE,
CONVERT(VARCHAR, A.HORA, 108) AS HORA,
B.NOME,
B.RA,
B.CPF,
B.ATRASO,
B.VL_DIVIDA,
B.IMPORT,
B.IMPORT_ACO,
CASE WHEN (CASE WHEN IMPORT IS NULL THEN IMPORT_ACO ELSE IMPORT END) = 002 THEN 'FASE 1' ELSE 'FASE 2' END AS FASE_DE

FROM 

[ADCOBMIS01].[dbo].[ALEGA_PAGAMENTO_AVON_V2] A
INNER JOIN [ADCOBMIS01].[dbo].[CARTEIRA_AVON_V2] B ON A.EC = B.EC AND CONVERT(DATE, B.DATA_BASE, 103) = CONVERT(DATE, A.DATA_BASE, 103)
WHERE A.DATA_BASE BETWEEN '2020-07-01' AND '2020-07-30'