SELECT
A.DATA_DA_TENTATIVA,
A.CARTEIRA_2,
COUNT(DISTINCT(A.DOCUMENTO)) AS ACESSOS,
SUM(CAST((CASE WHEN A.CONTRA_PROPOSTA = 'Não' THEN 0 ELSE 1 END) AS INT)) AS CONTRA_PROPOSTA,
SUM(CASE WHEN A.LINHA_DIGITAVEL = '' THEN 0 ELSE 1 END)  AS EMISSAO_BOLETOS,
SUM(CASE WHEN B.DATPGTOTITBOL IS NULL THEN 0 ELSE 1 END) AS PAGAMENTO,
SUM(VALOR_RS) AS VALOR

FROM ADCOBMIS01..ACORDO_ONLINE_DADOS_LOG A
LEFT JOIN ADCOBDAT..FI011 B ON A.LINHA_DIGITAVEL = B.LINHADIGITA
WHERE YEAR(A.DATA_DA_TENTATIVA) = 2020
AND DATA_DA_TENTATIVA BETWEEN '20200101' AND CONVERT(DATE, GETDATE(), 103)
AND NOME_OK = 'ok'
GROUP BY
A.DATA_DA_TENTATIVA,
A.CARTEIRA_2
ORDER BY 
A.DATA_DA_TENTATIVA ASC




--SELECT *  FROM ADCOBMIS01..ACORDO_ONLINE_DADOS_LOG
--WHERE YEAR(DATA_DA_TENTATIVA) = 2020
--AND DATA_DA_TENTATIVA BETWEEN '20201001' AND '20201031'
--AND NOME_OK = 'ok'