
USE LOCALCOB_DW

GO 

DECLARE @ID_LOTE BIGINT
INSERT INTO [LOCALCOB_DW]..MIS_LOTE_SMS	(DT_CADATRO) VALUES (GETDATE())
SET @ID_LOTE = @@IDENTITY


INSERT INTO DBO.MIS_GERAR_SMS
	(TB_EMPRESA_ID, TAB_SMS_ATRASO_ID, MIS_LOTE_SMS_ID, NM_CPFCNPJ, NM_ATRASO,NM_NOME, NM_DDD, NM_TELEFONE, DT_GERADO, ID_CLIENTE, ID_CONTRATO)

SELECT DISTINCT
1 AS TB_EMPRESA_ID,
FATR.[ID],
@ID_LOTE AS ID_LOTE,
FCLI.CPF,
FCLI.ATRASO,
FCLI.NOME,
FTEL.DDD,
FTEL.NUMERO,
GETDATE() AS DT_GERADO,
FCLI.ID_CLIENTE,
FCLI.ID_CONTRATO
FROM [LOCALCOB_DW]..[CARTEIRA_AVON_V3_DIA] FCLI
INNER JOIN [ADCOBMIS01]..[AVON_ESCORAGEM_TELEFONES] FTEL ON FTEL.CPF=FCLI.[CPF]
INNER JOIN [LOCALCOB_DW]..[TAB_SMS_ATRASO] FATR ON FCLI.ATRASO >= FATR.[NM_ATRASO_INI] AND FCLI.ATRASO <= FATR.[NM_ATRASO_FIM] AND FATR.[TB_EMPRESA_ID]=1
WHERE LEN(FTEL.NUMERO) = 9
AND FCLI.IMPORT_cob = 002
AND FTEL.PRIORIDADE = 1


IF OBJECT_ID ('TEMPDB..##BASEFRASE') IS NOT NULL DROP TABLE ##BASEFRASE
select
cast(nm_ddd as varchar)+cast(nm_telefone as varchar) as telefone,
st_frase
INTO ##BASEFRASE
from [LOCALCOB_DW]..vw_mis_gerar_sms where mis_lote_sms_id=@ID_LOTE



/*==========================================EXPORTA_ARQUIVOS==============================================================*/
DECLARE @BCPSQL_SMS VARCHAR(2000),
@BCPFILENAME_SMS VARCHAR(200)
SET @BCPFILENAME_SMS = '\\10.155.4.51\itf_in\AVON\SMS\SMS_AVON_FASE_1'+'_'+REPLACE((CONVERT(VARCHAR,CONVERT(DATE,(GETDATE())))),'-','')+'.csv'
SET @BCPSQL_SMS = 'SELECT * FROM ##BASEFRASE'
SET @BCPSQL_SMS = 'BCP "' + @BCPSQL_SMS + '" QUERYOUT ' + @BCPFILENAME_SMS + ' -c -t; -r\n -CP850 -T -Slocalhost'
PRINT @BCPSQL_SMS 
 
DECLARE @RC_SMS VARCHAR(100)
EXEC @RC_SMS = MASTER..XP_CMDSHELL @BCPSQL_SMS