DELETE FROM ADCOBMIS01..AVON_CARTEIRA_DIA_V3_POWER
WHERE DATA_BASE = CONVERT(DATE, GETDATE(), 103)

INSERT INTO ADCOBMIS01..AVON_CARTEIRA_DIA_V3_POWER
SELECT
DATA_BASE, 
COUNT(RA) AS CONTRATOS,
COUNT(DISTINCT(RA)) AS CPF,
SUM(VL_SALDO) AS VL_SALDO,
CASE 
WHEN A.ATRASO < 8 THEN 'A - 08<'
WHEN A.ATRASO BETWEEN 8 AND 30 THEN 'B - 08 a 30'
WHEN A.ATRASO BETWEEN 31 AND 60 THEN 'C - 31 a 60'
WHEN A.ATRASO BETWEEN 61 AND 90 THEN 'D - 61 a 90'
WHEN A.ATRASO > 90 THEN 'E - 90<' END AS AGING_CLUSTER_2,
UF,
MAX(A.RISCO_COB) AS RISCO_COB,
MAX(A.CAMPANHA) AS CAMPANHA,
B.DIVISAO,
B.CLASSE_RISCO,
B.NIVEL_RISCO
FROM LOCALCOB_DW..CARTEIRA_AVON_V3 A
LEFT JOIN [ADCOBMIS01].[dbo].[AVON_SETOR] B ON A.SETOR = B.SETOR
WHERE IMPORT_cob = 002
AND DATA_BASE = CONVERT(DATE, GETDATE(), 103)


GROUP BY 
DATA_BASE,
CASE 
WHEN A.ATRASO < 8 THEN 'A - 08<'
WHEN A.ATRASO BETWEEN 8 AND 30 THEN 'B - 08 a 30'
WHEN A.ATRASO BETWEEN 31 AND 60 THEN 'C - 31 a 60'
WHEN A.ATRASO BETWEEN 61 AND 90 THEN 'D - 61 a 90'
WHEN A.ATRASO > 90 THEN 'E - 90<' END,
UF,
B.DIVISAO,
B.CLASSE_RISCO,
B.NIVEL_RISCO