USE ADCOBDAT

DECLARE @INICIO DATE
DECLARE @FIM DATE

SET @INICIO = '2020-05-01'
SET @FIM = '2020-08-31 23:59'


--==============================================BASE_PARCELAS==========================================================
IF OBJECT_ID('TEMPDB..#BASE1') IS NOT NULL DROP TABLE #BASE1
SELECT (CONVERT(VARCHAR,A.NUMCONTRDIV) + '-' + CONVERT(VARCHAR,A.NUMPARC)) AS CHAVE,
	A.CODEMPRESA,
	A.NUMCONTRDIV,
	A.NUMPARC,
	CONVERT(DATE,A.DATVCTOPARC) VENCIMENTO,
	CONVERT(DATE,A.DATCHEGBODERPARC) AS DIREC_PARCELA,
	CONVERT(MONEY,A.VLRPRINCPARC) AS PMT,
	CONVERT(DATE,A.DATPGTOPARC) AS DATA_PAGAMENTO,
	CONVERT(DATE,A.DATBXPARC) AS DATA_BAIXA,
CASE
	WHEN CONVERT(DATE,A.DATBXPARC) IS NOT NULL AND CONVERT(DATE,A.DATPGTOPARC) IS NULL THEN DATEDIFF(DAY,CONVERT(DATE,A.DATVCTOPARC),CONVERT(DATE,A.DATBXPARC))
	WHEN CONVERT(DATE,A.DATPGTOPARC) IS NOT NULL AND CONVERT(DATE,A.DATBXPARC) IS NOT NULL THEN DATEDIFF(DAY,CONVERT(DATE,A.DATVCTOPARC),CONVERT(DATE,A.DATPGTOPARC))
	ELSE DATEDIFF(DAY,CONVERT(DATE,A.DATVCTOPARC),CONVERT(DATE,GETDATE()))
END ATRASO,
CASE
	WHEN CONVERT(DATE,A.DATPGTOPARC) IS NOT NULL THEN 'PG'
	WHEN CONVERT(DATE,A.DATBXPARC) IS NOT NULL AND A.DATPGTOPARC IS NULL THEN 'DS'
	ELSE 'EM COBRANÇA'
END TIPO_BAIXA
INTO #BASE1
FROM CO003 A WITH(NOLOCK)
WHERE CODEMPRESA BETWEEN 3001 AND 3010
AND A.DATCHEGBODERPARC BETWEEN @INICIO AND @FIM
AND A.TIPPARC = 1


--=======================================INCLUSÃO DE TIPO PESSOAS=========================================================
IF OBJECT_ID('TEMPDB..#BASE2') IS NOT NULL DROP TABLE #BASE2
SELECT DISTINCT A.*,
	B.NOMCLI AS CLIENTE,
	LTRIM(RTRIM(B.CODCPFCNPJCLI)) AS CPF_CNPJ,
	B.TIPPESSCLI AS TIPO_PESSOA
INTO #BASE2
FROM #BASE1 A
INNER JOIN CO001 B WITH(NOLOCK) ON A.CODEMPRESA = B.CODEMPRESA AND A.NUMCONTRDIV = B.NUMCONTRDIV
INNER JOIN CO002 C WITH(NOLOCK) ON A.CODEMPRESA = C.CODEMPRESA AND A.NUMCONTRDIV = C.NUMCONTRDIV
WHERE ATRASO BETWEEN 12 AND 90
AND C.TIPCONTR NOT IN ('ADVLOP01','ADVLPJ01')

--======================================INCLUSÃO DO DIRECIONAMENTO DO CONTRATO==================================================
IF OBJECT_ID('TEMPDB..#BASE3') IS NOT NULL DROP TABLE #BASE3
SELECT A.*,
	B.NUMPARCPLANODIV AS PLANO,
	B.TIPCONTR,
	CONVERT(DATE,B.DATCHEGBODERDIV) DIREC_CONTRATO
INTO #BASE3
FROM #BASE2 A
LEFT JOIN CO002 B WITH(NOLOCK) ON A.CODEMPRESA = B.CODEMPRESA AND A.NUMCONTRDIV = B.NUMCONTRDIV


--=========================================================INCLUSÃO DE MAX ATRASO===============================================================================
IF OBJECT_ID('TEMPDB..#BASE4') IS NOT NULL DROP TABLE #BASE4
SELECT A.*,
	B.MAIOR_ATRASO
INTO #BASE4
FROM(
SELECT DISTINCT A.NUMCONTRDIV,
	MAX(A.ATRASO) AS MAIOR_ATRASO
FROM #BASE3 A
GROUP BY A.NUMCONTRDIV)B
INNER JOIN #BASE3 A ON B.NUMCONTRDIV = A.NUMCONTRDIV
ORDER BY A.NUMCONTRDIV


--===========================================INCLUSÃO DA SAFRA DA PARCELA============================================================
IF OBJECT_ID('TEMPDB..#BASE5') IS NOT NULL DROP TABLE #BASE5
SELECT DISTINCT *,
CASE
	WHEN A.ATRASO BETWEEN 09 AND 30 THEN '1. SAFRA 30'
	WHEN A.ATRASO BETWEEN 31 AND 60 THEN '2. SAFRA 60'
	WHEN A.ATRASO BETWEEN 61 AND 90 THEN '3. SAFRA 90'
END SAFRA
INTO #BASE5
FROM #BASE4 A


--=========================================================INFORMAÇÃO DE MESES DE DIR_PARC E CONTRATO===============================================================================
SET LANGUAGE 'BRAZILIAN'

IF OBJECT_ID('TEMPDB..#BASE6') IS NOT NULL DROP TABLE #BASE6
SELECT DISTINCT A.*,
	DATENAME(MONTH,DIREC_PARCELA) AS MES_DIREC_PARCELA,
	CAST(YEAR(DIREC_PARCELA)AS VARCHAR)+
	RIGHT('0'+CAST(MONTH(DIREC_PARCELA) AS VARCHAR),2) AS DIR_PARC,
	DATENAME(MONTH,DIREC_CONTRATO) AS MES_DIREC_CONTRATO,
	B.[DIA UTIL] AS DIA_UTIL
INTO #BASE6
FROM #BASE5 A
INNER JOIN AUTOMATIZACOES.DBO.Dia_Util B WITH (NOLOCK) ON A.DIREC_PARCELA = B.[DATA]
ORDER BY PMT DESC


--=========================================================INFORMAÇÃO DE CPC===============================================================================
IF OBJECT_ID('TEMPDB..#CPC') IS NOT NULL DROP TABLE #CPC
SELECT DISTINCT A.*,
	B.OCORRENCIA
INTO #CPC
FROM(
SELECT DISTINCT CODEMPRESA,
	NUMCONTRDIV,
	MAX(DATHISTCOB) AS ULTIMO_CPC
FROM ADCOBMIS01.DBO.TABELA_CPC_VOLKS
GROUP BY CODEMPRESA,
	NUMCONTRDIV)A
INNER JOIN ADCOBMIS01.DBO.TABELA_CPC_VOLKS B ON A.CODEMPRESA = B.CODEMPRESA AND A.NUMCONTRDIV = B.NUMCONTRDIV AND A.ULTIMO_CPC = B.DATHISTCOB

IF OBJECT_ID('TEMPDB..#BASE7') IS NOT NULL DROP TABLE #BASE7
SELECT DISTINCT A.*,
CASE
	WHEN B.ULTIMO_CPC IS NULL THEN 'SEM CPC'
	ELSE 'CPC'
END CPC,
	ISNULL(CONVERT(VARCHAR,B.ULTIMO_CPC),'NULL') AS ULTIMO_CPC,
	ISNULL(B.OCORRENCIA, 'NULL') AS OCORRENCIA
INTO #BASE7
FROM #BASE6 A
LEFT JOIN #CPC B WITH (NOLOCK) ON A.NUMCONTRDIV = B.NUMCONTRDIV AND A.CODEMPRESA = B.CODEMPRESA


--=======================================INFORMAÇÕES DE UF E CIDADE==================================================
IF OBJECT_ID('TEMPDB..#ENDERECOS') IS NOT NULL DROP TABLE #ENDERECOS
SELECT DISTINCT A.*
INTO #ENDERECOS
FROM CO092 A WITH (NOLOCK)
WHERE A.CODEMPRESA BETWEEN 3001 AND 3010
AND A.STAENDCLI IN ('A')

IF OBJECT_ID('TEMPDB..#ENDERECOS2') IS NOT NULL DROP TABLE #ENDERECOS2
SELECT DISTINCT A.*,
	B.DCRCIDCLI AS CIDADE,
	B.CODUFCLI AS UF
INTO #ENDERECOS2
FROM(
SELECT DISTINCT A.CODEMPRESA,
	A.NUMCONTRDIV,
	MAX(A.SEQENDCLI) AS SEQENDCLI
FROM #ENDERECOS A
GROUP BY A.CODEMPRESA,
	A.NUMCONTRDIV)A
INNER JOIN #ENDERECOS B ON A.CODEMPRESA = B.CODEMPRESA AND A.NUMCONTRDIV = B.NUMCONTRDIV AND A.SEQENDCLI = B.SEQENDCLI
ORDER BY A.NUMCONTRDIV

IF OBJECT_ID('TEMPDB..#BASE8') IS NOT NULL DROP TABLE #BASE8
SELECT DISTINCT A.*,
	B.CIDADE,
	B.UF
INTO #BASE8
FROM #BASE7 A
LEFT JOIN #ENDERECOS2 B ON A.CODEMPRESA = B.CODEMPRESA AND A.NUMCONTRDIV = B.NUMCONTRDIV


IF OBJECT_ID('TEMPDB..#BASE_CP') IS NOT NULL DROP TABLE #BASE_CP
SELECT DISTINCT *,
	(CONVERT(VARCHAR(MAX),CONVERT(NUMERIC,NR_CONTRATO)) + '-' + CONVERT(VARCHAR(MAX),CONVERT(NUMERIC,NR_PARCELA))) AS CHAVE
INTO #BASE_CP
FROM ADCOBMIS01.DBO.BASE_CP_LOCAL

IF OBJECT_ID('TEMPDB..#BASE9') IS NOT NULL DROP TABLE #BASE9
SELECT DISTINCT A.CHAVE,
CASE
	WHEN SUM(CONVERT(MONEY,B.VALOR_ABERT_PRINCIPAL_ADV_SUM)) IS NULL THEN A.PMT
	ELSE SUM(CONVERT(MONEY,B.VALOR_ABERT_PRINCIPAL_ADV_SUM))
END AS VALOR_PRINCIPAL_CP,
	CONVERT(DATE,B.DATA_PAGTO_PARCELA) AS DT_PGTO_CP
INTO #BASE9
FROM #BASE8 A
LEFT JOIN #BASE_CP B ON A.CHAVE = B.CHAVE
GROUP BY A.CHAVE,
	A.PMT,
	CONVERT(DATE,B.DATA_PAGTO_PARCELA)

IF OBJECT_ID('TEMPDB..#BASE10') IS NOT NULL DROP TABLE #BASE10
SELECT DISTINCT A.*,
	B.VALOR_PRINCIPAL_CP,
	ISNULL(CONVERT(VARCHAR,B.DT_PGTO_CP),'-') AS DT_PGTO_CP
INTO #BASE10
FROM #BASE8 A
LEFT JOIN #BASE9 B ON A.CHAVE = B.CHAVE

SELECT DISTINCT A.*,
	B.RISCO_FSAG,
	B.GRUPO_RISCO,
	B.BASES_ACAO_CRISE_COVID
FROM #BASE10 A
LEFT JOIN ADCOBMIS01.DBO.BASE_BANCO_VOLKS B ON A.NUMCONTRDIV = B.NO_CONTRATO

--======================================================== FIM =====================================================*/

IF OBJECT_ID('TEMPDB..#INCON') IS NOT NULL DROP TABLE #INCON
SELECT DISTINCT NUMCONTRDIV,
	NUMPARC AS PARCELA,
	TIPO_PESSOA,
	DATA_PAGAMENTO,
	DATA_BAIXA,
	PMT,
	DT_PGTO_CP
INTO #INCON
FROM #BASE10
WHERE DATA_PAGAMENTO <= (SELECT MAX(CONVERT(DATE,DATA_PAGTO_PARCELA)) FROM #BASE_CP)



SELECT DISTINCT A.*
FROM #INCON A
LEFT JOIN #BASE_CP B ON A.NUMCONTRDIV = B.NR_CONTRATO AND A.PARCELA = B.NR_PARCELA AND A.TIPO_PESSOA = B.TIPOPES_CLIENTE
WHERE B.ANOMES_ABERT IS NULL