IF OBJECT_ID('tempdb..##BASEX1') IS NOT NULL DROP TABLE ##BASEX1
SELECT 
DATA_BASE,
EC,
RA,
CPF,
ID_CONTRATO,
CONTRATO,
ATRASO,
DEPOSITO,
VL_DIVIDA,
FAIXA_ATRASO,
[REGIÃO],
SEXO,
FASE,
RIGHT(CONTRATO,4) AS ANO_CAMPANHA,
LEFT(RIGHT(CONTRATO,6),2) AS CAMPANHA
INTO ##BASEX1
FROM  ADCOBMIS01..CARTEIRA_AVON_V2
where DATA_BASE = '2020-07-06' --CONVERT(DATE, getdate()-3,103)



IF OBJECT_ID('tempdb..##POR_FX') IS NOT NULL DROP TABLE ##POR_FX
SELECT
DATA_BASE,
EC,
RA,
CPF,
ID_CONTRATO,
CONTRATO,
ATRASO,
CASE
WHEN ATRASO <	5			THEN 	't.<5 dias'
WHEN ATRASO BETWEEN	5	AND	7	THEN 	'a.5 a 7 dias'
WHEN ATRASO BETWEEN	8	AND	15	THEN 	'b.8 a 15 dias'
WHEN ATRASO BETWEEN	16	AND	30	THEN 	'c.16 a 30 dias'
WHEN ATRASO BETWEEN	31	AND	60	THEN 	'd.31 a 60 dias'
WHEN ATRASO BETWEEN	61	AND	69	THEN 	'e.61 a 69 dias'
WHEN ATRASO BETWEEN	70	AND	90	THEN 	'f.70 a 90 dias'
WHEN ATRASO BETWEEN	91	AND	180	THEN 	'g.91 a 180 dias'
WHEN ATRASO BETWEEN	181	AND	270	THEN 	'h.181 a 270 dias'
WHEN ATRASO BETWEEN	271	AND	360	THEN 	'i.271 a 360 dias'
WHEN ATRASO BETWEEN	361	AND	720	THEN 	'j.361 a 720 dias'
WHEN ATRASO BETWEEN	721	AND	1080	THEN 	'k.721 a 1080 dias'
WHEN ATRASO BETWEEN	1081	AND	1440	THEN 	'l.1081 a 1440 dias'
WHEN ATRASO BETWEEN	1441	AND	1800	THEN 	'm.1441 a 1800 dias'
WHEN ATRASO BETWEEN	1801	AND	2160	THEN 	'n.1801 a 2160 dias'
WHEN ATRASO BETWEEN	2161	AND	2520	THEN 	'o.2161 a 2520 dias'
WHEN ATRASO BETWEEN	2521	AND	2880	THEN 	'p.2521 a 2880 dias'
WHEN ATRASO BETWEEN	2881	AND	3240	THEN 	'q.2881 a 3240 dias'
WHEN ATRASO BETWEEN	3241	AND	3600	THEN 	'r.3241 a 3600 dias'
WHEN ATRASO >	3600			THEN 	's. Acima 3600 dias'
END AS FX_ATRASO,
ANO_CAMPANHA,
CAMPANHA,
VL_DIVIDA
INTO ##POR_FX
FROM ##BASEX1
WHERE CAMPANHA = 11
AND ANO_CAMPANHA = 2020
--AND STATUS_CERTO NOT IN('BLACKLIST 1', 'ALEGA PAGAMENTO', 'CONTESTACAO', 'BLACK LIST 2', 'FRAUDE')
AND STATUS_CERTO IS NOT NULL
--SELECT * FROM ##POR_FX


/*total 90Mil*/
SELECT 
FX_ATRASO,
COUNT(FX_ATRASO) AS QUANTIDADE,
SUM(VL_DIVIDA) AS VALOR
FROM ##POR_FX
GROUP BY
FX_ATRASO

ORDER BY FX_ATRASO ASC



/*---------------------------------------*/

IF OBJECT_ID('tempdb..##BASEX2') IS NOT NULL DROP TABLE ##BASEX2
SELECT A.*, CASE WHEN B.ACCT_NR IS NOT NULL THEN 'CAMPANHA_11' END AS CAMPANHA_11_NAO_COBRAVEL
INTO ##BASEX2
FROM ##BASEX1 A 
LEFT JOIN ADCOBMIS01..CARTEIRA_11_AVON B ON a.CPF = replace(REPLACE(replace(INVC_REP_CPF_NR,'.',''),'-',''),' ','') 
where ANO_CAMPANHA = 2020


--SELECT * FROM ##BASEX2
IF OBJECT_ID('tempdb..##BASEX3') IS NOT NULL DROP TABLE ##BASEX3
SELECT * INTO ##BASEX3 
FROM(
SELECT
EC,
RA,
CPF,
ID_CONTRATO,
CONTRATO,
ATRASO,
CAMPANHA_11_NAO_COBRAVEL,
CASE
WHEN DEPOSITO =   '>90 DIAS - AVON'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   '05 A 07 DIAS - AVON'					THEN  'DEMAIS BASES'
WHEN DEPOSITO =   '08 A 15 ATRASO - C - AVON'			THEN  'DEMAIS BASES'
WHEN DEPOSITO =   '16 A 30 - AVON'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   '31 A 60 - AVON'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   '61 A 90 - AVON'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'ALEGA PAGAMENTO - AVON'				THEN  'ALEGA PAGAMENTO'
WHEN DEPOSITO =   'BLACKLIST - AVON'					THEN  'BLACKLIST 1'
WHEN DEPOSITO =   'BLACKLIST TEMPORARIA - AVON'			THEN  'CAMPANHA 11'
WHEN DEPOSITO =   'CARGA'								THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'COLCHAO - AVON'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'CONTESTACAO E FRAUDE - AVON'			THEN  'CONTESTACAO'
WHEN DEPOSITO =   'CPC - AVON'							THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'ENTRADAS - 08 A 15 - FASE 1 - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'ENTRADAS - 16 A 30 - FASE 1 - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'ENTRADAS - 31 A 60 - FASE 1 - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'ENTRADAS - 61 A 90 - FASE 1 - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'FASE 2 - CPC - 0 A 180'				THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'FASE 2 - CPC - 180 A 360'			THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'FASE 2 - QUEBRA'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'FRAUDE - AVON'						THEN  'FRAUDE'
WHEN DEPOSITO =   'HIGIENIZAÇÃO - AVON'					THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'INATIVO <18 REAIS - AVON'			THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'LOTES IMPORTANTES - AGING A - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'LOTES IMPORTANTES - AGING B - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'NAO COBRAR - AVON'					THEN  'BLACK LIST 2'
WHEN DEPOSITO =   'PREVENTIVO - >D1 - AVON'				THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'PREVENTIVO - D0 - AVON'				THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'PREVENTIVO - D1 - AVON'				THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'QUEBRA - AVON'						THEN  'DEMAIS BASES'
END AS 'STATUS'
FROM ##BASEX2
)A

WHERE A.STATUS NOT IN ('FRAUDE', 'ALEGA PAGAMENTO', 'CONTESTACAO','BLACK LIST 1', 'BLACK LIST 2')

/*----CAMPANHA 11----*/
IF OBJECT_ID('tempdb..##BASECAMP11') IS NOT NULL DROP TABLE ##BASECAMP11
SELECT * INTO ##BASECAMP11 
FROM(
SELECT
EC,
RA,
CPF,
ID_CONTRATO,
CONTRATO,
ATRASO,
CAMPANHA_11_NAO_COBRAVEL,
CASE
WHEN DEPOSITO =   '>90 DIAS - AVON'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   '05 A 07 DIAS - AVON'					THEN  'DEMAIS BASES'
WHEN DEPOSITO =   '08 A 15 ATRASO - C - AVON'			THEN  'DEMAIS BASES'
WHEN DEPOSITO =   '16 A 30 - AVON'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   '31 A 60 - AVON'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   '61 A 90 - AVON'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'ALEGA PAGAMENTO - AVON'				THEN  'ALEGA PAGAMENTO'
WHEN DEPOSITO =   'BLACKLIST - AVON'					THEN  'BLACKLIST 1'
WHEN DEPOSITO =   'BLACKLIST TEMPORARIA - AVON'			THEN  'CAMPANHA 11'
WHEN DEPOSITO =   'CARGA'								THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'COLCHAO - AVON'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'CONTESTACAO E FRAUDE - AVON'			THEN  'CONTESTACAO'
WHEN DEPOSITO =   'CPC - AVON'							THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'ENTRADAS - 08 A 15 - FASE 1 - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'ENTRADAS - 16 A 30 - FASE 1 - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'ENTRADAS - 31 A 60 - FASE 1 - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'ENTRADAS - 61 A 90 - FASE 1 - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'FASE 2 - CPC - 0 A 180'				THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'FASE 2 - CPC - 180 A 360'			THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'FASE 2 - QUEBRA'						THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'FRAUDE - AVON'						THEN  'FRAUDE'
WHEN DEPOSITO =   'HIGIENIZAÇÃO - AVON'					THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'INATIVO <18 REAIS - AVON'			THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'LOTES IMPORTANTES - AGING A - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'LOTES IMPORTANTES - AGING B - AVON'	THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'NAO COBRAR - AVON'					THEN  'BLACK LIST 2'
WHEN DEPOSITO =   'PREVENTIVO - >D1 - AVON'				THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'PREVENTIVO - D0 - AVON'				THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'PREVENTIVO - D1 - AVON'				THEN  'DEMAIS BASES'
WHEN DEPOSITO =   'QUEBRA - AVON'						THEN  'DEMAIS BASES'
END AS 'STATUS'
FROM ##BASEX2
)A

WHERE CAMPANHA_11_NAO_COBRAVEL = 'CAMPANHA_11'


SELECT * FROM ##BASEX3

/*CAMPANHA 11 NÃO COBRÁVEL*/
SELECT
CASE 
WHEN ATRASO BETWEEN 0 AND 4 THEN 'Menor 5'
WHEN ATRASO BETWEEN 5 AND 7 THEN '5 a 7'
WHEN ATRASO BETWEEN 8 AND 30 THEN '8 a 30'
WHEN ATRASO BETWEEN 31 AND 60 THEN '31 a 60'
WHEN ATRASO BETWEEN 61 AND 90 THEN '61 a 90'
WHEN ATRASO > 90 THEN 'Maior 90' END AS CLUSTER,
COUNT(CAMPANHA_11_NAO_COBRAVEL) AS CAMPANHA_11_N_COBR
FROM ##BASEX3
WHERE ATRASO >0
GROUP BY 
CASE 
WHEN ATRASO BETWEEN 0 AND 4 THEN 'Menor 5'
WHEN ATRASO BETWEEN 5 AND 7 THEN '5 a 7'
WHEN ATRASO BETWEEN 8 AND 30 THEN '8 a 30'
WHEN ATRASO BETWEEN 31 AND 60 THEN '31 a 60'
WHEN ATRASO BETWEEN 61 AND 90 THEN '61 a 90'
WHEN ATRASO > 90 THEN 'Maior 90' END

/*DEMAIS BASES*/
SELECT
CASE 
WHEN ATRASO BETWEEN 0 AND 4 THEN 'Menor 5'
WHEN ATRASO BETWEEN 5 AND 7 THEN '5 a 7'
WHEN ATRASO BETWEEN 8 AND 30 THEN '8 a 30'
WHEN ATRASO BETWEEN 31 AND 60 THEN '31 a 60'
WHEN ATRASO BETWEEN 61 AND 90 THEN '61 a 90'
WHEN ATRASO > 90 THEN 'Maior 90' END AS CLUSTER,
[STATUS] AS 'STATUS',
COUNT(DISTINCT(EC)) AS QUANTIDADE
FROM ##BASEX3
WHERE ATRASO >0
GROUP BY 
CASE 
WHEN ATRASO BETWEEN 0 AND 4 THEN 'Menor 5'
WHEN ATRASO BETWEEN 5 AND 7 THEN '5 a 7'
WHEN ATRASO BETWEEN 8 AND 30 THEN '8 a 30'
WHEN ATRASO BETWEEN 31 AND 60 THEN '31 a 60'
WHEN ATRASO BETWEEN 61 AND 90 THEN '61 a 90'
WHEN ATRASO > 90 THEN 'Maior 90' END,
[STATUS]

--IF OBJECT_ID('tempdb..##teste') IS NOT NULL DROP TABLE ##teste

/*DEMAIS BASES POR CAMPANHA*/
SELECT
--CONTRATO,
CASE
WHEN ATRASO BETWEEN 0 AND 4 THEN 'Menor 5'
WHEN ATRASO BETWEEN 5 AND 7 THEN '5 a 7'
WHEN ATRASO BETWEEN 8 AND 30 THEN '8 a 30'
WHEN ATRASO BETWEEN 31 AND 60 THEN '31 a 60'
WHEN ATRASO BETWEEN 61 AND 90 THEN '61 a 90'
WHEN ATRASO > 90 THEN 'Maior 90' END AS CLUSTER,
LEFT(RIGHT(CONTRATO,6),2) AS CAMPANHA,
[STATUS] AS 'STATUS',
COUNT(DISTINCT(EC)) AS QUANTIDADE
FROM ##BASEX3
WHERE ATRASO > 0
GROUP BY 
CASE 
WHEN ATRASO BETWEEN 0 AND 4 THEN 'Menor 5'
WHEN ATRASO BETWEEN 5 AND 7 THEN '5 a 7'
WHEN ATRASO BETWEEN 8 AND 30 THEN '8 a 30'
WHEN ATRASO BETWEEN 31 AND 60 THEN '31 a 60'
WHEN ATRASO BETWEEN 61 AND 90 THEN '61 a 90'
WHEN ATRASO > 90 THEN 'Maior 90' END,
[STATUS],
LEFT(RIGHT(CONTRATO,6),2)

--select
--CLUSTER,
--CAMPANHA,
--STATUS,
--COUNT(CAMPANHA) AS CLIENTES

--from SELECT * FROM ##teste
--GROUP BY 
--CLUSTER,
--CAMPANHA,
--STATUS