IF OBJECT_ID('tempdb..##BATI_AVON') IS NOT NULL DROP TABLE ##BATI_AVON

SELECT
CAST (DATA_BASE AS VARCHAR) AS DATA_BASE,
CAST (ID_CLIENTE AS VARCHAR) AS ID_CLIENTE,
CAST (RA AS VARCHAR) AS RA,
CAST (NOME AS VARCHAR) AS NOME,
CAST (CPF AS VARCHAR) AS CPF,
CAST (SEXO AS VARCHAR) AS SEXO,
CAST (ID_CONTRATO AS VARCHAR) AS ID_CONTRATO,
CAST (CONTRATO AS VARCHAR) AS CONTRATO,
CAST (CAMPANHA AS VARCHAR) AS CAMPANHA,
CAST (ANO_CAMPANHA AS VARCHAR) AS ANO_CAMPANHA,
CAST (UF AS VARCHAR) AS UF,
CAST (DT_VENCIMENTO AS VARCHAR) AS DT_VENCIMENTO,
CAST (ATRASO AS VARCHAR) AS ATRASO,
CAST (DT_INCLUSAO AS VARCHAR) AS DT_INCLUSAO,
CAST (ID_DIVIDA AS VARCHAR) AS ID_DIVIDA,
CAST (VL_SALDO AS VARCHAR) AS VL_SALDO,
CAST (FAIXA_ATRASO AS VARCHAR) AS FAIXA_ATRASO,
CAST (LOA AS VARCHAR) AS LOA,
CAST (SETOR AS VARCHAR) AS SETOR,
CAST (QUINTIL AS VARCHAR) AS QUINTIL,
CAST (FASE_COB AS VARCHAR) AS FASE_COB,
CAST (RISCO_COB AS VARCHAR) AS RISCO_COB,
CAST (IMPORT_cob AS VARCHAR) AS IMPORT_cob,
CAST (ACORDO_ATIVO AS VARCHAR) AS ACORDO_ATIVO,
CAST (DT_ACORDO AS VARCHAR) AS DT_ACORDO,
CAST (DEPOSITO AS VARCHAR) AS DEPOSITO,
CAST (CONT_CONTRATOS AS VARCHAR) AS CONT_CONTRATOS

INTO ##BATI_AVON FROM LOCALCOB_DW..CARTEIRA_AVON_V3_DIA
WHERE IMPORT_cob = 002

INSERT INTO ##BATI_AVON

SELECT		
'DATA_BASE'			AS DATA_BASE,
'ID_CLIENTE'		AS ID_CLIENTE,
'RA'				AS RA,
'NOME'				AS NOME,
'CPF'				AS CPF,
'SEXO'				AS SEXO,
'ID_CONTRATO'		AS ID_CONTRATO,
'CONTRATO'			AS CONTRATO,
'CAMPANHA'			AS CAMPANHA,
'ANO_CAMPANHA'		AS ANO_CAMPANHA,
'UF'				AS UF,
'DT_VENCIMENTO'		AS DT_VENCIMENTO,
'ATRASO'			AS ATRASO,
'DT_INCLUSAO'		AS DT_INCLUSAO,
'ID_DIVIDA'			AS ID_DIVIDA,
'VL_SALDO'			AS VL_SALDO,
'FAIXA_ATRASO'		AS FAIXA_ATRASO,
'LOA'				AS LOA,
'SETOR'				AS SETOR,
'QUINTIL'			AS QUINTIL,
'FASE_COB'			AS FASE_COB,
'RISCO_COB'			AS RISCO_COB,
'IMPORT_cob'		AS IMPORT_cob,
'ACORDO_ATIVO'		AS ACORDO_ATIVO,
'DT_ACORDO'			AS DT_ACORDO,
'DEPOSITO'			AS DEPOSITO,
'CONT_CONTRATOS'	AS CONT_CONTRATOS	


DECLARE @BCPSQL_ALM2		VARCHAR(2000),
		@BCPFILENAME_ALM2	VARCHAR(200)
SET		@BCPFILENAME_ALM2 = '\\10.155.4.51\itf_in\AVON\BATIMENTO\BATIMENTO_AVON_F1'+'_'+REPLACE((CONVERT(VARCHAR,CONVERT(DATE,(GETDATE())))),'-','')+'.csv'
SET		@BCPSQL_ALM2 =		'SELECT * FROM ##BATI_AVON ORDER BY 1 DESC'
SET		@BCPSQL_ALM2 =		'BCP "' + @BCPSQL_ALM2 + '" QUERYOUT ' + @BCPFILENAME_ALM2 + ' -c -t; -r\n -CP850 -T -Slocalhost'
PRINT	@BCPSQL_ALM2
DECLARE @RC_ALM2 VARCHAR(100)
EXEC	@RC_ALM2 = MASTER..XP_CMDSHELL @BCPSQL_ALM2