
--INSERT INTO ADCOBMIS01..CARTEIRAS_POWER_BI
SELECT
'5001' AS CODEMPRESA,

CASE 
WHEN FASE = 'FASE 1' THEN 'BRADESCO FIN - FASE 1'
WHEN FASE = 'FASE 2' THEN 'BRADESCO FIN - FASE 2, 3 E LP'
WHEN FASE = 'FASE 3' THEN 'BRADESCO FIN - FASE 3'
WHEN FASE = 'LP2'	 THEN 'BRADESCO FIN - LP'
WHEN FASE = 'LP3' 	 THEN 'BRADESCO FIN - FASE 3'
WHEN FASE = 'SIG'	 THEN 'BRADESCO FIN - FASE 1'
END AS CORTE,
COUNT(CONTRATO) AS QUANTIDADE


FROM BRADESCO_CARTEIRA

GROUP BY

CASE 
WHEN FASE = 'FASE 1' THEN 'BRADESCO FIN - FASE 1'
WHEN FASE = 'FASE 2' THEN 'BRADESCO FIN - FASE 2, 3 E LP'
WHEN FASE = 'FASE 3' THEN 'BRADESCO FIN - FASE 3'
WHEN FASE = 'LP2'	 THEN 'BRADESCO FIN - LP'
WHEN FASE = 'LP3' 	 THEN 'BRADESCO FIN - FASE 3'
WHEN FASE = 'SIG'	 THEN 'BRADESCO FIN - FASE 1'
END 
