
IF OBJECT_ID('tempdb..##ULT_DAT_M') IS NOT NULL DROP TABLE ##ULT_DAT_M
IF OBJECT_ID('tempdb..##ULT_DAT_A') IS NOT NULL DROP TABLE ##ULT_DAT_A

SELECT MAX(DATA) AS ULT_DAT INTO ##ULT_DAT_M FROM ADCOBMIS01..CPY_RM_GERAL GROUP BY MONTH(CONVERT(DATE, DATA,103))

SELECT 
CASE WHEN  ULT_DAT = GETDATE()-1 THEN (

select MAX(DATA) FROM (
SELECT DATA FROM ADCOBMIS01..CPY_RM_GERAL 
WHERE DATA BETWEEN DATEADD(MM,0,DATEADD(DD,-DAY(GETDATE())+1,(SUBSTRING(CONVERT(VARCHAR,(GETDATE()),120),1,10)) + ' 00:00:00')) AND DATEADD(MM,1,DATEADD(DD,-DAY(GETDATE()),(SUBSTRING(CONVERT(VARCHAR,(GETDATE()),120),1,10)) + ' 23:59:59'))
and DATEPART(DW, CONVERT(DATE, DATA, 103)) = 2)A
)
ELSE ULT_DAT END AS ULTM_DATA
INTO ##ULT_DAT_A
FROM ##ULT_DAT_M

SELECT 
DATA_CPY AS DATA,
MES,
CARGO,
CARTEIRA,
QUANTIDADE

FROM (
SELECT 
CONVERT(DATE, A.DATA,103) AS DATA_CPY,
       CASE
         WHEN MONTH(CONVERT(DATE, A.DATA,103)) = 1 THEN 'JANEIRO'
         WHEN MONTH(CONVERT(DATE, A.DATA,103)) = 2 THEN 'FEVEREIRO'
         WHEN MONTH(CONVERT(DATE, A.DATA,103)) = 3 THEN 'MARÇO'
         WHEN MONTH(CONVERT(DATE, A.DATA,103)) = 4 THEN 'ABRIL'
         WHEN MONTH(CONVERT(DATE, A.DATA,103)) = 5 THEN 'MAIO'
         WHEN MONTH(CONVERT(DATE, A.DATA,103)) = 6 THEN 'JUNHO'
         WHEN MONTH(CONVERT(DATE, A.DATA,103)) = 7 THEN 'JULHO'
         WHEN MONTH(CONVERT(DATE, A.DATA,103)) = 8 THEN 'AGOSTO'
         WHEN MONTH(CONVERT(DATE, A.DATA,103))= 9 THEN 'SETEMBRO'
         WHEN MONTH(CONVERT(DATE, A.DATA,103))= 10 THEN 'OUTUBRO'
         WHEN MONTH(CONVERT(DATE, A.DATA,103)) = 11 THEN 'NOVEMBRO'
         WHEN MONTH(CONVERT(DATE, A.DATA,103)) = 12 THEN 'DEZEMBRO'
       END AS 'MES',
A.NOME1 AS CARGO,
A.CARTEIRA,
COUNT(A.CARTEIRA) AS QUANTIDADE
FROM (

SELECT DISTINCT
A.CHAPA,
A.NOME,
A.CODSITUACAO,
A.DATA_ADMISSÃO,
CASE WHEN A.NOME1 = 'ESTAGIARIO DE COBRANCA' THEN 'ESTAG' ELSE 'CLT' END AS NOME1,
A.CODCCUSTO,
A.[SITUAÇÃO DO CONTRATO],
A.CARTEIRA,
A.CODFUNCAO,
A.DESCRICAO_FUNCAO,
A.DATA

FROM ADCOBMIS01..CPY_RM_GERAL A


)A

GROUP BY 
A.NOME1,
A.DATA,
A.CARTEIRA
)B
INNER JOIN ##ULT_DAT_A C ON B.DATA_CPY = C.ULTM_DATA


ORDER BY DATA ASC