IF OBJECT_ID('tempdb..##EMI_INMANO') IS NOT NULL DROP TABLE ##EMI_INMANO

DECLARE @INICIO DATE
DECLARE @FIM DATE
SET @INICIO = '2020-01-01'
SET @FIM = '2020-12-31'


SELECT DISTINCT B.COD_CRED AS EMPRESA,
	B.CONTRATO_TIT AS CONTRATO,
	LTRIM(RTRIM(D.NOME_PES)) AS CLIENTE,
LTRIM(RTRIM(CASE
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 1  THEN ('0000000000' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 2  THEN ('000000000' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 3  THEN ('00000000' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 4  THEN ('0000000' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 5  THEN ('000000' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 6  THEN ('00000' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 7  THEN ('0000' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 8  THEN ('000' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 9  THEN ('00' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 10 THEN ('0' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 11 THEN (CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 12 THEN ('00' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 13 THEN ('0' + CONVERT(VARCHAR,D.CPFCGC_PES))
	WHEN LEN(CONVERT(VARCHAR,D.CPFCGC_PES)) = 14 THEN (CONVERT(VARCHAR,D.CPFCGC_PES))
	ELSE CONVERT(VARCHAR, D.CPFCGC_PES)
END)) CPF_CNPJ,
	CONVERT(DATE,A.DATAVENCIMENTO) AS DATA_VENCIMENTO,
	CONVERT(DATE,A.DATADOCUMENTO) AS DATA_EMISSAO,
	CONVERT(DATE,E.DT_PGTO_REC) AS DATA_PAGAMENTO,
	(CONVERT(MONEY,A.ValorVencimento)) - ((CONVERT(MONEY,A.ValorVencimento)*10)/100) AS VALOR_REPASSE,
	((CONVERT(MONEY,A.ValorVencimento)*10)/100) AS VALOR_HONORARIO,
	CONVERT(MONEY,A.ValorVencimento) AS VALOR_BOLETO,
	UPPER(LTRIM(RTRIM(G.NOME_PES))) AS OPERADOR_EMISSÃO,
	DATEDIFF(DAY,CONVERT(DATE,A.DATADOCUMENTO),MIN(VCTO_PARC)) AS ATRASO_EMISSAO,
	A.Parc_ini AS PARCELA_ACORDO,
CASE
	WHEN B.PLANO_TIT = 1 THEN 'A VISTA'
	ELSE 'PARCELADO'
END TIPO_ACORDO,
CASE
	WHEN CONVERT(DATE,E.DT_PGTO_REC) IS NULL THEN 'EM ANDAMENTO'
	ELSE 'PAGO'
END STATUS_ACORDO,
	REPLACE(REPLACE(A.ImpNossoNum,'/',''),'-','') AS NOSSO_NUMERO,
	'10%' AS "% DE H.O",
	B.PLANO_TIT AS PLANO,
	A.LINHADIGITAVEL
	INTO ##EMI_INMANO
FROM [VCOM].[LOCALCRED_Cobsystems].[DBO].BOLETOS_EM A
LEFT JOIN [VCOM].[LOCALCRED_Cobsystems].[DBO].[TITULOS] B ON A.COD_TIT = B.COD_TIT
LEFT JOIN [VCOM].[LOCALCRED_Cobsystems].[DBO].[DEVEDORES] C ON B.COD_DEV = C.COD_DEV
LEFT JOIN [VCOM].[LOCALCRED_Cobsystems].[DBO].[PESSOAS] D ON C.COD_PES = D.COD_PES
LEFT JOIN [VCOM].[LOCALCRED_Cobsystems].[DBO].[RECEBIMENTOS] E ON A.COD_BEM = E.COD_BEM
LEFT JOIN [VCOM].[LOCALCRED_Cobsystems].[DBO].[LOGIN] F ON A.USUARIO_CAD = F.COD_LOGIN
LEFT JOIN [VCOM].[LOCALCRED_Cobsystems].[DBO].[PESSOAS] G ON F.COD_PES = G.COD_PES
LEFT JOIN [VCOM].[LOCALCRED_Cobsystems].[DBO].[PARCELAS] H ON A.COD_TIT = H.COD_TIT
WHERE B.COD_CRED = 13
AND CONVERT(DATE,A.DATADOCUMENTO) = CONVERT(DATE, GETDATE()-1, 103) --BETWEEN @INICIO AND @FIM
GROUP BY B.COD_CRED,
	B.CONTRATO_TIT,
	LTRIM(RTRIM(D.NOME_PES)),
	D.CPFCGC_PES,
	A.DATAVENCIMENTO,
	A.DATADOCUMENTO,
	E.DT_PGTO_REC,
	A.ValorVencimento,
	G.NOME_PES,
	A.Parc_ini,
	B.PLANO_TIT,
	A.ImpNossoNum,
	A.LINHADIGITAVEL


	 
DECLARE @BCPSQL_SMS VARCHAR(2000),
@BCPFILENAME_SMS VARCHAR(200)
SET @BCPFILENAME_SMS = '\\10.155.4.51\itf_in\INMANO\BOLETOS\INMANO_BOLETOS'+'_'+REPLACE((CONVERT(VARCHAR,CONVERT(DATE,(GETDATE())))),'-','')+'.csv'
SET @BCPSQL_SMS = 'SELECT * FROM ##EMI_INMANO'
SET @BCPSQL_SMS = 'BCP "' + @BCPSQL_SMS + '" QUERYOUT ' + @BCPFILENAME_SMS + ' -c -t; -r\n -CP850 -T -Slocalhost'
PRINT @BCPSQL_SMS 
 
DECLARE @RC_SMS VARCHAR(100)
EXEC @RC_SMS = MASTER..XP_CMDSHELL @BCPSQL_SMS
 
