DECLARE @INI DATE SET @INI = CAST(DATEADD(MM, DATEDIFF(MM,0,GETDATE()), 0) AS DATE) 
DECLARE @FIM DATE SET @FIM = CAST(DATEADD(MM, DATEDIFF(MM,0,GETDATE())+1, -1) AS DATE)

	IF OBJECT_ID('tempdb..##BASEAVON') IS NOT NULL DROP TABLE ##BASEAVON
SELECT DISTINCT 
A.ID_ACORDO,
CONVERT(VARCHAR,DT_ACORDO,103) AS DATA_ACORDO,
CONVERT(VARCHAR,DT_ACORDO,108) AS HORA_ACORDO,
CONVERT(VARCHAR,F.DT_PARCELA ,103) AS VENCIMENTO,
CASE F.NU_PARCELA WHEN 1 THEN 'NN' ELSE 'COLCHÃO' END AS TIPO,
CAST(F.NU_PARCELA AS VARCHAR)+'/'+CAST(A.NU_PLANO AS VARCHAR) PARCELAS,
    CAST(f.VL_PARCELA AS MONEY) AS VL_PARCELA, 
    CAST(I.VL_RECEITA AS MONEY) AS VL_RECEITA,--resseita
    --VL_RECEITA+VL_REPASSE
    CASE 
     WHEN F.TP_STATUS = 0 AND F.DT_PARCELA <  CAST(GETDATE() AS DATE) THEN 'AGUARDANDO BAIXA'
	 WHEN F.TP_STATUS = 0 AND F.DT_PARCELA >= CAST(GETDATE() AS DATE) THEN 'ABERTA' 
	 WHEN F.TP_STATUS = 1 THEN 'PAGO'
	 WHEN F.TP_STATUS = 2 THEN 'CANCELADO' 
    END	AS STATUS_PARC,
	CASE 
	 WHEN A.TP_STATUS = 0 THEN 'PROMESSA' 
	 WHEN A.TP_STATUS = 1 THEN 'ACORDO' 
	 WHEN A.TP_STATUS = 2 THEN 'QUITADO' 
	 WHEN A.TP_STATUS = 3 THEN 'CANCELADO' 
    END	AS STATUS_ACORDO,
    CASE 
     WHEN i.tp_fatura IN ( 0, 1 ) THEN 'DIRETO' 
     WHEN I.tp_fatura IN ( 2, 3, 4 ) THEN 'INDIRETO' 
	 WHEN A.TP_STATUS = 3 THEN 'CANCELADO' 
    END                                                 DIR_IND, --Direto e indireto
    CONVERT(VARCHAR,I.DT_PAGAMENTO,103) AS DT_PAGAMENTO,--data pagamento
	CONVERT(VARCHAR,A.DT_CANCELAMENTO,103) AS DT_CANCELAMENTO,
	CASE 
	 WHEN F.TP_STATUS = 0 AND F.DT_PARCELA <  CAST(GETDATE() AS DATE) THEN DATEDIFF(DAY,F.DT_PARCELA,GETDATE())
	 ELSE DATEDIFF(DAY,DT_ACORDO,A.DT_CANCELAMENTO) 
	END AS ATRASO_ACORDO, 
B.ID_CLIENTE AS EC,
C.NM_CLIENTE_CEDENTE AS RA,
C.NM_NOME AS NOME,
C.NU_CPF_CNPJ AS CPF,
ltrim(rtrim(CASE WHEN G.NM_USUARIO IS NULL THEN 'INDIRETO' ELSE G.NM_USUARIO END)) AS OPERADOR,
D.ID_CONTRATO,
NM_CONTRATO_CEDENTE AS CONTRATO,
CONVERT(VARCHAR,B.DT_VENCIMENTO,103) AS VENC_ORIGINAL,
--HOUR(DT_ACORDO) HORA,
FASE.FASE,
RISCO.NM_DETALHE_VALOR AS RISCO,
DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) ATRASO,
CASE FASE.FASE WHEN 'FASE 1' THEN
CASE WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) BETWEEN  8 AND 15  THEN 'FASE 1 - 08 A 15'
	 WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) BETWEEN 16 AND 30  THEN 'FASE 1 - 16 A 30'
	 WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) BETWEEN 31 AND 60  THEN 'FASE 1 - 31 A 60'
	 WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) BETWEEN 61 AND 90  THEN 'FASE 1 - 61 A 90'
	 WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) BETWEEN 5 AND 7  THEN 'FASE 1 - 05 A 07'
	 WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) < 5  THEN 'FASE 1 - <05'
	 WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) >90  THEN 'FASE 1 - >90'
	 ELSE 'FASE 1 - FORA DA FAIXA'
	 END
WHEN 'FASE 2' THEN
CASE WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) BETWEEN   91 AND 180   THEN 'FASE 2'
	 WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) BETWEEN  181 AND 360   THEN 'FASE 3'
	 WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) BETWEEN  361 AND 1080  THEN 'FASE 4'
	 WHEN DATEDIFF(D,B.DT_VENCIMENTO,DT_ACORDO) > 1081				  THEN 'FASE 5'
	 ELSE 'FASE 2 - FORA DA FAIXA'
	 END
END AS PERFORMANTE
--TEL.DDD+TEL.NUMERO AS TELEFONE
INTO ##BASEAVON 
FROM [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_ACORDO] A (NOLOCK)
LEFT JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_ACORDO_DIVIDA] B (NOLOCK) ON B.ID_ACORDO = A.ID_ACORDO
LEFT JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_CLIENTE] C (NOLOCK) ON C.ID_CLIENTE = B.ID_CLIENTE
LEFT JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_CONTRATO] D WITH (NOLOCK) ON D.ID_CONTRATO = B.ID_CONTRATO
LEFT JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_DIVIDA] E WITH (NOLOCK) ON D.ID_CONTRATO = E.ID_CONTRATO
LEFT JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_ACORDO_PARCELA] F WITH(NOLOCK) ON F.ID_ACORDO=A.ID_ACORDO AND F.ID_CLIENTE=A.ID_CLIENTE
LEFT JOIN (SELECT ID_CONTRATO,ID_ACORDO,NM_DETALHE_VALOR,CASE WHEN NM_DETALHE_VALOR = '002' THEN 'FASE 1' WHEN NM_DETALHE_VALOR = '506' THEN  'FASE 2' ELSE '' END as FASE
		   FROM [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_ACORDO_DIVIDA_DETALHE] WHERE ID_DETALHE = 351) FASE ON FASE.ID_CONTRATO = D.ID_CONTRATO
LEFT JOIN (SELECT ID_CONTRATO,ID_ACORDO,NM_DETALHE_VALOR
		   FROM [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_ACORDO_DIVIDA_DETALHE] WHERE ID_DETALHE = 121) RISCO ON /*FASACO.ID_ACORDO = A.ID_ACORDO AND*/ RISCO.ID_CONTRATO = D.ID_CONTRATO
LEFT JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_USUARIO] G WITH (NOLOCK) ON G.ID_USUARIO = A.ID_USUARIO
LEFT OUTER JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_FATURA] I  WITH (NOLOCK) ON I.ID_CLIENTE = F.ID_CLIENTE AND I.ID_ACORDO = F.ID_ACORDO AND I.NU_PARCELA = F.NU_PARCELA AND I.TP_STATUS IN( 0, 1 )
--LEFT JOIN ADCOBMIS01.DBO.AVON_TELEFONES TEL ON TEL.NU_CPF_CNPJ = C.NU_CPF_CNPJ
WHERE ID_CEDENTE = 1
AND CAST(DT_ACORDO AS DATE) BETWEEN @INI AND @FIM 
--AND CAST(F.DT_PARCELA AS DATE) = CAST(GETDATE() AS DATE)--VENCENDO HOJE




SELECT ROW_NUMBER()over(partition by RA order by RA) AS QTD_CTT, * FROM ##BASEAVON
