SELECT
PG.NUMCONTRDIV AS CONTRATO,
PG.CODEMPRESA AS EMPRESA,
PG.NUMCONTRDIV AS CONTRATO,
CONVERT(DATE, PG.DATEMITITBOL, 103) AS [DATA_EMISSAO],
MAX(CONVERT(DATE, PG.DATVENCTITBOL, 103)) AS [DATA_VENCIMENTO],
CONVERT(DATE, PG.DATPGTOTITBOL, 103) AS [DATA_PAGAMENTO],
CASE
	WHEN CONVERT(DATE, PG.DATPGTOTITBOL, 103) < =  CONVERT(DATE, PG.DATVENCTITBOL, 103)  THEN CONVERT(DATE, PG.DATVENCTITBOL, 103)  ELSE CONVERT(DATE, PG.DATPGTOTITBOL, 103)  END AS [DATA_PAGAMENTO_2],
PG.NUMFAIXATRASTITBOL AS ATRASO,

CASE
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 91 AND 120		THEN 'A - 91 A 120'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 121 AND 150		THEN 'B - 121 A 150'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 151 AND 180   	THEN 'C - 151 A 180'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 181 AND 360		THEN 'D - 181 A 360'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 361 AND 520		THEN 'E - 361 A 540'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 521 AND 720		THEN 'F - 541 A 720'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 721 AND 1080		THEN 'G - 721 A 1080'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 1081 AND 1800	THEN 'H - 1081 A 1800'
	WHEN PG.NUMFAIXATRASTITBOL				  > 1800	THEN 'I - ACIMA DE 1800' END AS FX_ATRASO,

	CASE
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 0 AND 180		THEN 'A - 46 A 180'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 181 AND 360		THEN 'B - 181 A 360'
	WHEN PG.NUMFAIXATRASTITBOL > 360                	THEN 'C - Maior 361' END AS FX_ATRASO_2,

CAST(SD.VLRSALDHISTPLDIV AS MONEY) AS SALDO,
PG.VLRTITBOL AS REPASSE,
CAST(CASE
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 0 AND 360	THEN PG.VLRTITBOL * 0.1 ELSE PG.VLRTITBOL * 0.2 END AS MONEY) AS 'HO',


PG.USEREMTITBOL AS LOGIN_ADCOB,
LG.NOME AS USUARIO_EMISSAO,
SCORECONTR AS SCORE_CONTRATANTE,
SD.STAFASECOBRDIV AS FASE,
SD.DCRPRODCONTRDIV AS PRODUTO,
PAN.CODPRODCONTRDIV,
CASE
	WHEN PAN.CODPRODCONTRDIV = 1 THEN	'PESADOS'
	WHEN PAN.CODPRODCONTRDIV = 2 THEN	'LEVES'
	WHEN PAN.CODPRODCONTRDIV = 3 THEN	'MOTOS'
	WHEN PAN.CODPRODCONTRDIV = 4 THEN	'REVENDAS' ELSE '' END AS SEGUIMENTO,


CASE 

	WHEN	SD.DCRPRODCONTRDIV = 	'LEVES PF MULTIMARCA'			THEN	'LEVES'
	WHEN	SD.DCRPRODCONTRDIV = 	'ÔNIBUS PF'						THEN	'PESADOS'
	WHEN	SD.DCRPRODCONTRDIV = 	'UTILITÁRIOS PF'				THEN	'REVENDAS'
	WHEN	SD.DCRPRODCONTRDIV = 	'CAMINHÃO PF'					THEN	'PESADOS'
	WHEN	SD.DCRPRODCONTRDIV = 	'MOTOS PF'						THEN	'MOTOS'
	WHEN	SD.DCRPRODCONTRDIV = 	'BALCÃO PF LEVES'				THEN	'LEVES'
	WHEN	SD.DCRPRODCONTRDIV = 	'LEVES PF CONCESSIONÁRIA'		THEN	'LEVES'
	WHEN	SD.DCRPRODCONTRDIV = 	'RENEG. PF LEVES MULTIMARCA'	THEN	'LEVES'
	WHEN	SD.DCRPRODCONTRDIV = 	'AUTOPAN PF LEVES'				THEN	'LEVES'
	WHEN	SD.DCRPRODCONTRDIV = 	'AUTOPAN PJ CAMINHÃO'			THEN	'PESADOS'
	WHEN	SD.DCRPRODCONTRDIV = 	'BALCÃO PF CAMINHÃO'			THEN	'PESADOS'
	WHEN	SD.DCRPRODCONTRDIV = 	'BALCÃO PF UTILITÁRIO'			THEN	'REVENDAS' ELSE '' END AS PRODUTO_2,

MAX(CAST(CA.VLRNEGOCIADO AS money)) AS RISCO,
PG.CODUFTITBOL AS UF


FROM ADCOBDAT..FI011 PG /* TABELA EMISSÃO E PAGAMENTOS RAIZ*/
INNER JOIN ADCOBDAT..VW_LOGINS LG ON LG.LOGIN = PG.USEREMTITBOL /* VIEW DE LOGINS OPERADORES*/
INNER JOIN ADCOBDAT..CO002 SD ON PG.NUMCONTRDIV = SD.NUMCONTRDIV /* INFORMAÇÃO COMPLEMENTAR DE CARGA 1*/
LEFT JOIN ADCOBDAT..CO131 CA  ON PG.NUMCONTRDIV = CA.NUMCONTRDIV /* COMPLETA FI011*/
LEFT JOIN ADCOBDAT..CO268 CB  ON CA.IDACORDO = CB.IDACORDO AND PG.NUMCONTRDIV = CA.NUMCONTRDIV /*COMPLETA A FI011 E CO131*/
LEFT JOIN ADCOBMIS01..ESTRATIFICACAO_BANCO_PAN PAN ON PG.NUMCONTRDIV = PAN.NUMCONTRDIV

WHERE PG.CODEMPRESA BETWEEN 66001 AND 66002
AND CONVERT(DATE, PG.DATVENCTITBOL, 103) BETWEEN '2020-08-01' AND CONVERT(DATE, GETDATE(), 103)
AND CA.STAACORDO = 'PG'
AND CONVERT(DATE, PG.DATPGTOTITBOL, 103) IS NOT NULL
---AND PG.NUMCONTRDIV = '080901772'

GROUP BY 

PG.NUMCONTRDIV,
PG.CODEMPRESA,
CONVERT(DATE, PG.DATEMITITBOL, 103),
CONVERT(DATE, PG.DATPGTOTITBOL, 103),
PG.DATVENCTITBOL,
PG.CODEMPRESA,
PG.NUMFAIXATRASTITBOL,

CASE
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 91 AND 120		THEN 'A - 91 A 120'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 121 AND 150		THEN 'B - 121 A 150'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 151 AND 180   	THEN 'C - 151 A 180'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 181 AND 360		THEN 'D - 181 A 360'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 361 AND 520		THEN 'E - 361 A 540'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 521 AND 720		THEN 'F - 541 A 720'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 721 AND 1080		THEN 'G - 721 A 1080'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 1081 AND 1800	THEN 'H - 1081 A 1800'
	WHEN PG.NUMFAIXATRASTITBOL				  > 1800	THEN 'I - ACIMA DE 1800' END,
		CASE
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 0 AND 180		THEN 'A - 46 A 180'
	WHEN PG.NUMFAIXATRASTITBOL BETWEEN 181 AND 360		THEN 'B - 181 A 360'
	WHEN PG.NUMFAIXATRASTITBOL > 360                	THEN 'C - Maior 361' END,

CAST(SD.VLRSALDHISTPLDIV AS MONEY) ,
CONVERT(DATE, PG.DATPGTOTITBOL, 103),
PG.VLRTITBOL,
PG.USEREMTITBOL,
LG.NOME,
SCORECONTR,
SD.STAFASECOBRDIV,
SD.DCRPRODCONTRDIV,
PAN.CODPRODCONTRDIV,

CASE
	WHEN PAN.CODPRODCONTRDIV = 1 THEN	'PESADOS'
	WHEN PAN.CODPRODCONTRDIV = 2 THEN	'LEVES'
	WHEN PAN.CODPRODCONTRDIV = 3 THEN	'MOTOS'
	WHEN PAN.CODPRODCONTRDIV = 4 THEN	'REVENDAS' ELSE '' END,
SD.VLRSALDHISTPLDIV,
CASE 

	WHEN	SD.DCRPRODCONTRDIV = 	'LEVES PF MULTIMARCA'			THEN	'LEVES'
	WHEN	SD.DCRPRODCONTRDIV = 	'ÔNIBUS PF'						THEN	'PESADOS'
	WHEN	SD.DCRPRODCONTRDIV = 	'UTILITÁRIOS PF'				THEN	'REVENDAS'
	WHEN	SD.DCRPRODCONTRDIV = 	'CAMINHÃO PF'					THEN	'PESADOS'
	WHEN	SD.DCRPRODCONTRDIV = 	'MOTOS PF'						THEN	'MOTOS'
	WHEN	SD.DCRPRODCONTRDIV = 	'BALCÃO PF LEVES'				THEN	'LEVES'
	WHEN	SD.DCRPRODCONTRDIV = 	'LEVES PF CONCESSIONÁRIA'		THEN	'LEVES'
	WHEN	SD.DCRPRODCONTRDIV = 	'RENEG. PF LEVES MULTIMARCA'	THEN	'LEVES'
	WHEN	SD.DCRPRODCONTRDIV = 	'AUTOPAN PF LEVES'				THEN	'LEVES'
	WHEN	SD.DCRPRODCONTRDIV = 	'AUTOPAN PJ CAMINHÃO'			THEN	'PESADOS'
	WHEN	SD.DCRPRODCONTRDIV = 	'BALCÃO PF CAMINHÃO'			THEN	'PESADOS'
	WHEN	SD.DCRPRODCONTRDIV = 	'BALCÃO PF UTILITÁRIO'			THEN	'REVENDAS' ELSE '' END ,
PG.CODUFTITBOL
