
DECLARE @INI DATE SET @INI = '2020-07-10'--CAST(DATEADD(MM, DATEDIFF(MM,0,GETDATE()), 0) AS DATE) 
DECLARE @FIM DATE SET @FIM = '2020-07-10'--CAST(DATEADD(MM, DATEDIFF(MM,0,GETDATE())+1, -1) AS DATE)

SELECT DISTINCT 
A.ID_ACORDO,
CONVERT(VARCHAR,DT_ACORDO,103) AS DATA_ACORDO,
CONVERT(VARCHAR,DT_ACORDO,108) AS HORA_ACORDO,
LEFT(CONVERT(VARCHAR,DT_ACORDO,108),2) AS HORA,
CONVERT(VARCHAR,F.DT_PARCELA ,103) AS VENCIMENTO,
CASE F.NU_PARCELA WHEN 1 THEN 'NN' ELSE 'COLCHÃO' END AS TIPO,
CAST(F.NU_PARCELA AS VARCHAR)+'/'+CAST(A.NU_PLANO AS VARCHAR) PARCELAS,
    CAST(f.VL_PARCELA AS MONEY) AS VL_PARCELA, 
    CAST(I.VL_RECEITA AS MONEY) AS VL_RECEITA,--resseita

    CASE 
     WHEN F.TP_STATUS = 0 AND F.DT_PARCELA <  CAST(GETDATE() AS DATE) THEN 'AGUARDANDO BAIXA'
	 WHEN F.TP_STATUS = 0 AND F.DT_PARCELA >= CAST(GETDATE() AS DATE) THEN 'ABERTA' 
	 WHEN F.TP_STATUS = 1 THEN 'PAGO'
	 WHEN F.TP_STATUS = 2 THEN 'CANCELADO' 
    END	AS STATUS_PARC,
	CASE 
	 WHEN A.TP_STATUS = 0 THEN 'PROMESSA' 
	 WHEN A.TP_STATUS = 1 THEN 'ACORDO' 
	 WHEN A.TP_STATUS = 2 THEN 'QUITADO' 
	 WHEN A.TP_STATUS = 3 THEN 'CANCELADO'
    END	AS STATUS_ACORDO,
	A.DT_ACORDO,
	A.DT_CANCELAMENTO,
	CASE WHEN CONVERT(DATE, A.DT_ACORDO, 103) = CONVERT(DATE, A.DT_CANCELAMENTO, 103) THEN 0 ELSE 3 END AS BELIAU,
    CASE 
     WHEN i.tp_fatura IN ( 0, 1 ) THEN 'DIRETO' 
     WHEN I.tp_fatura IN ( 2, 3, 4 ) THEN 'INDIRETO' 
	 WHEN A.TP_STATUS = 3 THEN 'CANCELADO' 
    END                                                 DIR_IND, --Direto e indireto
    CONVERT(VARCHAR,I.DT_PAGAMENTO,103) AS DT_PAGAMENTO,--data pagamento
	CONVERT(VARCHAR,A.DT_CANCELAMENTO,103) AS DT_CANCELAMENTO,
	CASE 
	 WHEN F.TP_STATUS = 0 AND F.DT_PARCELA <  CAST(GETDATE() AS DATE) THEN DATEDIFF(DAY,F.DT_PARCELA,GETDATE())
	 ELSE DATEDIFF(DAY,DT_ACORDO,A.DT_CANCELAMENTO) 
	END AS ATRASO_ACORDO, 
AC_DIV.ID_CLIENTE AS EC,
NM_CLIENTE_CEDENTE AS RA,
NM_NOME AS NOME,
RTRIM(LTRIM(LEFT(RTRIM(LTRIM(LEFT(G.NM_USUARIO,CHARINDEX(' ',G.NM_USUARIO )+1))),12)))+'.'  AS PRI_NOME_OP,
NU_CPF_CNPJ AS CPF,
ltrim(rtrim(CASE WHEN G.NM_USUARIO IS NULL THEN 'INDIRETO' ELSE G.NM_USUARIO END)) AS OPERADOR,
D.ID_CONTRATO,
NM_CONTRATO_CEDENTE AS CONTRATO,
CONVERT(VARCHAR,AC_DIV.DT_VENCIMENTO,103) AS VENC_ORIGINAL,
CASE
	WHEN FASE.NM_DETALHE_VALOR = '002' THEN 'FASE1'
	WHEN FASE.NM_DETALHE_VALOR = '506' THEN 'FASE2' END AS FASE,
	RISCO.NM_DETALHE_VALOR AS RISCO,

DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) ATRASO,

CASE FASE.NM_DETALHE_VALOR WHEN '002' THEN
CASE WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) BETWEEN  8 AND 15  THEN 'FASE 1 - 08 A 15'
	 WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) BETWEEN 16 AND 30  THEN 'FASE 1 - 16 A 30'
	 WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) BETWEEN 31 AND 60  THEN 'FASE 1 - 31 A 60'
	 WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) BETWEEN 61 AND 90  THEN 'FASE 1 - 61 A 90'
	 WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) BETWEEN  5 AND 7	THEN 'FASE 1 - 05 A 07'
	 WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) < 5				THEN 'FASE 1 - <05'
	 WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) >90				THEN 'FASE 1 - >90'
	 ELSE 'FASE 1 - FORA DA FAIXA'
	 END
WHEN '506' THEN
CASE WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) BETWEEN     91 AND 180   THEN 'FASE 2'
	 WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) BETWEEN     181 AND 360   THEN 'FASE 3'
	 WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) BETWEEN     361 AND 1080  THEN 'FASE 4'
	 WHEN DATEDIFF(D,AC_DIV.DT_VENCIMENTO,DT_ACORDO) > 1081				    THEN 'FASE 5'
	 ELSE 'FASE 2 - FORA DA FAIXA'
	 END
END AS PERFORMANTE,
MONTH(A.DT_ACORDO) AS MES_NUMBER,
CASE
		WHEN MONTH(A.DT_ACORDO)	= 1  THEN 'JANEIRO'
		WHEN MONTH(A.DT_ACORDO)	= 2  THEN 'FEVEREIRO'
		WHEN MONTH(A.DT_ACORDO)	= 3  THEN 'MARÇO'
		WHEN MONTH(A.DT_ACORDO)	= 4  THEN 'ABRIL'
		WHEN MONTH(A.DT_ACORDO)	= 5  THEN 'MAIO'
		WHEN MONTH(A.DT_ACORDO)	= 6  THEN 'JUNHO'
		WHEN MONTH(A.DT_ACORDO)	= 7  THEN 'JULHO'
		WHEN MONTH(A.DT_ACORDO)	= 8  THEN 'AGOSTO'
		WHEN MONTH(A.DT_ACORDO)	= 9  THEN 'SETEMBRO'
		WHEN MONTH(A.DT_ACORDO)	= 10 THEN 'OUTUBRO'
		WHEN MONTH(A.DT_ACORDO)	= 11 THEN 'NOVEMBRO'
		WHEN MONTH(A.DT_ACORDO)	= 12 THEN 'DEZEMBRO'
		END AS 'MES',
YEAR(A.DT_ACORDO) AS ANO

FROM TB_ACORDO A (NOLOCK)

LEFT JOIN TB_ACORDO_DIVIDA AC_DIV (NOLOCK) ON AC_DIV.ID_CLIENTE = A.ID_CLIENTE
LEFT JOIN TB_CLIENTE CLIENTE (NOLOCK) ON CLIENTE.ID_CLIENTE = AC_DIV.ID_CLIENTE
LEFT JOIN TB_CONTRATO D WITH (NOLOCK) ON D.ID_CONTRATO = AC_DIV.ID_CONTRATO
LEFT JOIN TB_DIVIDA E WITH (NOLOCK) ON D.ID_CONTRATO = E.ID_CONTRATO
LEFT JOIN TB_ACORDO_PARCELA F WITH(NOLOCK) ON F.ID_ACORDO=A.ID_ACORDO AND F.ID_ACORDO=A.ID_ACORDO
LEFT JOIN TB_ACORDO_DIVIDA_DETALHE FASE ON FASE.ID_ACORDO = A.ID_ACORDO

LEFT JOIN (SELECT ID_CONTRATO,ID_ACORDO,NM_DETALHE_VALOR FROM TB_ACORDO_DIVIDA_DETALHE WHERE ID_DETALHE = 121) RISCO ON RISCO.ID_ACORDO = A.ID_ACORDO

LEFT JOIN TB_USUARIO G WITH (NOLOCK) ON G.ID_USUARIO = A.ID_USUARIO
LEFT OUTER JOIN TB_FATURA I  WITH (NOLOCK) ON I.ID_CLIENTE = F.ID_CLIENTE AND I.ID_ACORDO = F.ID_ACORDO AND I.NU_PARCELA = F.NU_PARCELA AND I.TP_STATUS IN( 0, 1 )
WHERE ID_CEDENTE = 1
AND CAST(DT_ACORDO AS DATE) BETWEEN @INI AND @FIM 
AND ID_DETALHE IN (351)
--and i.tp_fatura IN ( 0, 1 )
and FASE.NM_DETALHE_VALOR = '002'
--and G.NM_USUARIO IS NOT NULL
AND A.ID_ACORDO in (6694351, 6694352)


SELECT DISTINCT * FROM (	
SELECT
CASE 
WHEN CONVERT(DATE, DT_CANCELAMENTO, 103) = CONVERT(DATE, DT_ACORDO, 103) AND TP_STATUS = 3


THEN 'CANCELADO' ELSE 'PROMESSA' END AS BELIAU, 
ID_ACORDO,
ID_USUARIO,
ID_CLIENTE,
TP_STATUS

 FROM TB_ACORDO
WHERE CONVERT(DATE, DT_ACORDO, 103)  = '2020-07-01'
--AND TP_STATUS = 0
AND ID_USUARIO IS NOT NULL
) A 
WHERE A.BELIAU = 'PROMESSA'
--AND A.ID_CLIENTE = 347870
AND A.TP_STATUS IN (0, 1, 2)
ORDER BY A.ID_CLIENTE ASC

--WHERE ID_ACORDO = 6694351
