IF OBJECT_ID('tempdb..##BASE_BOLHA_PBI') IS NOT NULL DROP TABLE ##BASE_BOLHA_PBI

SELECT 
DATA_BASE 			 AS  DATA_BASE , 
ID_CLIENTE 			 AS  ID_CLIENTE, 
RA 					 AS  RA, 
NOME 				 AS  NOME, 
CPF 				 AS  CPF, 
SEXO 				 AS  SEXO, 
ID_CONTRATO 		 AS  ID_CONTRATO, 
CONTRATO 			 AS  CONTRATO, 
CAMPANHA 			 AS  CAMPANHA, 
ANO_CAMPANHA 		 AS  ANO_CAMPANHA, 
UF 					 AS  UF, 
DT_VENCIMENTO 		 AS  DT_VENCIMENTO, 
ATRASO 				 AS  ATRASO, 
DT_INCLUSAO 		 AS  DT_INCLUSAO, 
ID_DIVIDA 			 AS  ID_DIVIDA, 
VL_SALDO   			 AS  VL_SALDO, 
FAIXA_ATRASO 		 AS  FAIXA_ATRASO, 
LOA 				 AS  LOA, 
SETOR 				 AS  SETOR, 
QUINTIL 			 AS  QUINTIL, 
FASE_COB 			 AS  FASE_COB, 
RISCO_COB 			 AS  RISCO_COB, 
IMPORT_cob 			 AS  IMPORT_cob, 
ACORDO_ATIVO 		 AS  ACORDO_ATIVO, 
DT_ACORDO 			 AS  DT_ACORDO, 
DEPOSITO 			 AS  DEPOSITO, 
CONT_CONTRATOS 		 AS  CONT_CONTRATOS 		
 INTO ##BASE_BOLHA_PBI
	FROM 
	LOCALCOB_DW.dbo.CARTEIRA_AVON_V3 fv3
	where
	convert(date,fv3.DT_INCLUSAO,103) >= '20200901'
	AND fv3.IMPORT_cob='002'
	and fv3.DATA_BASE = (select min(t.DATA_BASE ) from LOCALCOB_DW.dbo.CARTEIRA_AVON_V3 t where t.IMPORT_cob ='002' and t.ID_CLIENTE = fv3.ID_CLIENTE  and convert(date,t.DT_INCLUSAO,103) >= '20200901')
	ORDER BY CPF,1;

	SELECT
	DT_INCLUSAO,
	CASE 
		WHEN ATRASO BETWEEN	-99999  AND 7 THEN  '<7'
		WHEN ATRASO BETWEEN		 8  AND 30 THEN '8 A 30'
		WHEN ATRASO BETWEEN		 31 AND 60 THEN '31 A 60'
		WHEN ATRASO BETWEEN      61 AND 90 THEN '61 A 90'
		ELSE '> 90' END AS FX_ATRASO,

			CASE 
		WHEN ATRASO BETWEEN	-99999  AND 7 THEN  'A'
		WHEN ATRASO BETWEEN		 8  AND 30 THEN 'B'
		WHEN ATRASO BETWEEN		 31 AND 60 THEN 'C'
		WHEN ATRASO BETWEEN      61 AND 90 THEN 'D'
		ELSE 'E' END AS FX_ATRASO_CLASS,


	COUNT(DT_INCLUSAO) AS QUANTIDADE,
	SUM(VL_SALDO) AS SALDO
	
	FROM ##BASE_BOLHA_PBI

	GROUP BY 
	DT_INCLUSAO,
	CASE 
		WHEN ATRASO BETWEEN	-99999  AND 7 THEN  '<7'
		WHEN ATRASO BETWEEN		 8  AND 30 THEN '8 A 30'
		WHEN ATRASO BETWEEN		 31 AND 60 THEN '31 A 60'
		WHEN ATRASO BETWEEN      61 AND 90 THEN '61 A 90'
		ELSE '> 90' END,
	CASE 
		WHEN ATRASO BETWEEN	-99999  AND 7 THEN  'A'
		WHEN ATRASO BETWEEN		 8  AND 30 THEN 'B'
		WHEN ATRASO BETWEEN		 31 AND 60 THEN 'C'
		WHEN ATRASO BETWEEN      61 AND 90 THEN 'D'
		ELSE 'E' END

	ORDER BY 1 ASC