IF OBJECT_ID('tempdb..##BASE_FASE_1') IS NOT NULL DROP TABLE ##BASE_FASE_1

SELECT * INTO ##BASE_FASE_1 FROM LOCALCOB_DW..CARTEIRA_AVON_V3_DIA
WHERE IMPORT_cob = 002
AND CONVERT(DATE, DT_INCLUSAO, 103) = CONVERT(DATE, GETDATE(), 103)

DECLARE @BCPSQL_SMS VARCHAR(2000),
@BCPFILENAME_SMS VARCHAR(200)
SET @BCPFILENAME_SMS = '\\10.155.4.51\itf_in\AVON\ENTRADAS_FASE_1\ENTRADAS_FASE_1'+'_'+REPLACE((CONVERT(VARCHAR,CONVERT(DATE,(GETDATE())))),'-','')+'.CSV'
SET @BCPSQL_SMS = 'SELECT * FROM ##BASE_FASE_1'
SET @BCPSQL_SMS = 'BCP "' + @BCPSQL_SMS + '" QUERYOUT ' + @BCPFILENAME_SMS + ' -c -t; -r\n -CP850 -T -Slocalhost'
PRINT @BCPSQL_SMS 
 
DECLARE @RC_SMS VARCHAR(100)
EXEC @RC_SMS = MASTER..XP_CMDSHELL @BCPSQL_SMS