IF OBJECT_ID('tempdb..##BASE_FASE_1') IS NOT NULL DROP TABLE ##BASE_FASE_1

SELECT
CONVERT(VARCHAR, DATA_BASE, 102) AS DATA_BASE,
CAST(ID_CLIENTE AS VARCHAR) AS ID_CLIENTE,
CAST(RA AS VARCHAR) AS RA,
CAST(NOME AS VARCHAR) AS NOME,
CAST(CPF AS VARCHAR) AS CPF,
CAST(SEXO AS VARCHAR) AS SEXO,
CAST(ID_CONTRATO AS VARCHAR) AS ID_CONTRATO,
CAST(CONTRATO AS VARCHAR) AS CONTRATO,
CAST(CAMPANHA AS VARCHAR) AS CAMPANHA,
CAST(ANO_CAMPANHA AS VARCHAR) AS ANO_CAMPANHA,
CAST(UF AS VARCHAR) AS UF,
CAST(DT_VENCIMENTO AS VARCHAR) AS DT_VENCIMENTO,
CAST(ATRASO AS VARCHAR) AS ATRASO,
CAST(DT_INCLUSAO AS VARCHAR) AS DT_INCLUSAO,
CAST(ID_DIVIDA AS VARCHAR) AS ID_DIVIDA,
CAST(VL_SALDO AS VARCHAR) AS VL_SALDO,
CAST(FAIXA_ATRASO AS VARCHAR) AS FAIXA_ATRASO,
CAST(LOA AS VARCHAR) AS LOA,
CAST(SETOR AS VARCHAR) AS SETOR,
CAST(QUINTIL AS VARCHAR) AS QUINTIL,
CAST(FASE_COB AS VARCHAR) AS FASE_COB,
CAST(RISCO_COB AS VARCHAR) AS RISCO_COB,
CAST(IMPORT_cob AS VARCHAR) AS IMPORT_cob,
CAST(ACORDO_ATIVO AS VARCHAR) AS ACORDO_ATIVO,
CONVERT(VARCHAR, DT_ACORDO, 102) AS DT_ACORDO,
CAST(DEPOSITO AS VARCHAR) AS DEPOSITO,
CAST(CONT_CONTRATOS AS VARCHAR) AS CONT_CONTRATOS
INTO ##BASE_FASE_1
FROM LOCALCOB_DW..CARTEIRA_AVON_V3_DIA
WHERE IMPORT_cob = 002
AND CONVERT(DATE, DT_INCLUSAO, 103) = CONVERT(DATE, GETDATE(), 103)

INSERT INTO ##BASE_FASE_1
SELECT
'DATA_BASE' AS DATA_BASE,
'ID_CLIENTE' AS ID_CLIENTE,
'RA' AS RA,
'NOME' AS NOME,
'CPF' AS CPF,
'SEXO' AS SEXO,
'ID_CONTRATO' AS ID_CONTRATO,
'CONTRATO' AS CONTRATO,
'CAMPANHA' AS CAMPANHA,
'ANO_CAMPANHA' AS ANO_CAMPANHA,
'UF' AS UF,
'DT_VENCIMENTO' AS DT_VENCIMENTO,
'ATRASO' AS ATRASO,
'DT_INCLUSAO' AS DT_INCLUSAO,
'ID_DIVIDA' AS ID_DIVIDA,
'VL_SALDO' AS VL_SALDO,
'FAIXA_ATRASO' AS FAIXA_ATRASO,
'LOA' AS LOA,
'SETOR' AS SETOR,
'QUINTIL' AS QUINTIL,
'FASE_COB' AS FASE_COB,
'RISCO_COB' AS RISCO_COB,
'IMPORT_cob' AS IMPORT_cob,
'ACORDO_ATIVO' AS ACORDO_ATIVO,
'DT_ACORDO' AS DT_ACORDO,
'DEPOSITO' AS DEPOSITO,
'CONT_CONTRATOS' AS CONT_CONTRATOS




DECLARE @BCPSQL_SMS VARCHAR(2000),
@BCPFILENAME_SMS VARCHAR(200)
SET @BCPFILENAME_SMS = '\\10.155.4.51\itf_in\AVON\ENTRADAS_FASE_1\ENTRADAS_FASE_1'+'_'+REPLACE((CONVERT(VARCHAR,CONVERT(DATE,(GETDATE())))),'-','')+'.CSV'
SET @BCPSQL_SMS = 'SELECT * FROM ##BASE_FASE_1 ORDER BY 1 DESC'
SET @BCPSQL_SMS = 'BCP "' + @BCPSQL_SMS + '" QUERYOUT ' + @BCPFILENAME_SMS + ' -c -t; -r\n -CP850 -T -Slocalhost'
PRINT @BCPSQL_SMS 
 
DECLARE @RC_SMS VARCHAR(100)
EXEC @RC_SMS = MASTER..XP_CMDSHELL @BCPSQL_SMS


