--	IF OBJECT_ID('tempdb..##BASEJUL') IS NOT NULL DROP TABLE ##BASEJUL
--	DECLARE @DTINI DATE
--	DECLARE @DTFIM DATE
--	SET @DTINI = '2018-07-01'
--	SET @DTFIM = '2018-07-31'
--	SELECT * INTO ##BASEJUL FROM ADCOBMIS01..AVON_CARTEIRA_BKP WITH (NOLOCK)
--	WHERE DATA_BASE	BETWEEN @DTINI AND @DTFIM


--DECLARE @BCPSQL_SMS VARCHAR(2000),
--@BCPFILENAME_SMS VARCHAR(200)
--SET @BCPFILENAME_SMS = '\\10.155.4.51\itf_in\MIS\DADOS_AVON\CARTEIRA_AVON_BKP\CARTEIRA_AVON_BKP_072018.csv'
--SET @BCPSQL_SMS = 'SELECT * FROM ##BASEJUL'
--SET @BCPSQL_SMS = 'BCP "' + @BCPSQL_SMS + '" QUERYOUT ' + @BCPFILENAME_SMS + ' -c -t; -r\n -CP850 -T -Slocalhost'
--PRINT @BCPSQL_SMS 
--DECLARE @RC_SMS VARCHAR(100)
--EXEC @RC_SMS = MASTER..XP_CMDSHELL @BCPSQL_SMS



DELETE FROM ADCOBMIS01..AVON_CARTEIRA_BKP WITH(ROWLOCK)
WHERE DATA_BASE BETWEEN '2018-07-01' AND '2018-12-31'
GO