
IF OBJECT_ID('tempdb..##CTT_PAN_ENT') IS NOT NULL DROP TABLE ##CTT_PAN_ENT
IF OBJECT_ID('tempdb..##CTT_PAN_1') IS NOT NULL DROP TABLE ##CTT_PAN_1
IF OBJECT_ID('tempdb..##TOTAL') IS NOT NULL DROP TABLE ##TOTAL


SELECT DISTINCT
NUMCONTRDIV INTO ##CTT_PAN_1 FROM ADCOBMIS01..ESTRATIFICACAO_BANCO_PAN
WHERE DATA = '2020-08-03'


SELECT DISTINCT
NUMCONTRDIV INTO ##CTT_PAN_ENT FROM ADCOBMIS01..ESTRATIFICACAO_BANCO_PAN
WHERE DATCHEGBODERDIV >= '2020-08-03'


SELECT * INTO ##TOTAL FROM (
SELECT * FROM ##CTT_PAN_1
UNION ALL

SELECT * FROM ##CTT_PAN_ENT
)A


SELECT

A.NUMCONTRDIV,
B.CODEMPRESA,
D.NOMCLI AS NOME_CLIENTE,
D.CODCPFCNPJCLI AS CPF,
DATEDIFF(YEAR, D.DATNASCCLI, GETDATE()) AS IDADE_CLIENTE,
D.CODUFRESCLI AS UF,
B.SALDOATRASO,
B.PMT,
MAX(B.DATCHEGBODERDIV) AS DATA_ENTRADA,
MAX(B.FAIXAATRASO) as ATRASO,
CASE
	WHEN MAX(B.FAIXAATRASO) BETWEEN 91 AND 120		THEN 'A - 91 A 120'
	WHEN MAX(B.FAIXAATRASO) BETWEEN 121 AND 150		THEN 'B - 121 A 150'
	WHEN MAX(B.FAIXAATRASO) BETWEEN 151 AND 180   	THEN 'C - 151 A 180'
	WHEN MAX(B.FAIXAATRASO) BETWEEN 181 AND 360		THEN 'D - 181 A 360'
	WHEN MAX(B.FAIXAATRASO) BETWEEN 361 AND 520		THEN 'E - 361 A 540'
	WHEN MAX(B.FAIXAATRASO) BETWEEN 521 AND 720		THEN 'F - 541 A 720'
	WHEN MAX(B.FAIXAATRASO) BETWEEN 721 AND 1080	THEN 'G - 721 A 1080'
	WHEN MAX(B.FAIXAATRASO) BETWEEN 1081 AND 1800	THEN 'H - 1081 A 1800'
	WHEN MAX(B.FAIXAATRASO)				  > 1800	THEN 'I - ACIMA DE 1800' END AS FX_ATRASO,
	CASE
	WHEN MAX(B.FAIXAATRASO) BETWEEN 0 AND 180		THEN 'A - 46 A 180'
	WHEN MAX(B.FAIXAATRASO) BETWEEN 181 AND 360		THEN 'B - 181 A 360'
	WHEN MAX(B.FAIXAATRASO) > 360                	THEN 'C - Maior 361' END AS FX_ATRASO_2,


B.RISCONTR AS RISCO,
B.DCRPRODCONTRDIV AS PRODUTO,
CASE
	WHEN B.CODPRODCONTRDIV = 1 THEN	'PESADOS'
	WHEN B.CODPRODCONTRDIV = 2 THEN	'LEVES'
	WHEN B.CODPRODCONTRDIV = 3 THEN	'MOTOS'
	WHEN B.CODPRODCONTRDIV = 4 THEN	'REVENDAS' ELSE '' END AS SEGUIMENTO


FROM ##TOTAL A
LEFT JOIN ADCOBMIS01..ESTRATIFICACAO_BANCO_PAN B ON A.NUMCONTRDIV = B.NUMCONTRDIV
LEFT JOIN ADCOBMIS01..CO001 D ON A.NUMCONTRDIV = D.NUMCONTRDIV



GROUP BY

A.NUMCONTRDIV,
B.CODEMPRESA,
B.SALDOATRASO, 
D.NOMCLI,
D.CODCPFCNPJCLI,
DATEDIFF(YEAR, D.DATNASCCLI, GETDATE()),
D.CODUFRESCLI,
B.PMT,
B.RISCONTR,
B.DCRPRODCONTRDIV,
CASE
	WHEN B.CODPRODCONTRDIV = 1 THEN	'PESADOS'
	WHEN B.CODPRODCONTRDIV = 2 THEN	'LEVES'
	WHEN B.CODPRODCONTRDIV = 3 THEN	'MOTOS'
	WHEN B.CODPRODCONTRDIV = 4 THEN	'REVENDAS' ELSE '' END