SELECT
A.ID_CLIENTE,
CONVERT(DATE, B.DT_VENCIMENTO, 103) AS VENCIMENTO_ORIGINAL,
DATEDIFF(DAY, CONVERT(DATE, B.DT_VENCIMENTO, 103),GETDATE()) AS ATRASO,
A.NU_CPF_CNPJ AS CPF,
C.NM_CONTRATO_CEDENTE,
C.DT_ATUALIZACAO,
C.DT_CADASTRO,
C.DT_VENCIMENTO_CONTABIL,
C.TP_STATUS_CONTABIL,
B.VL_DIVIDA,
B.ID_CONTRATO


FROM TB_CLIENTE A, TB_DIVIDA B, TB_CONTRATO C
WHERE A.ID_CLIENTE = C.ID_CLIENTE AND B.ID_CONTRATO = C.ID_CONTRATO
AND B.ID_CONTRATO IN ()