IF OBJECT_ID('TEMPDB..#LOGINS') IS NOT NULL DROP TABLE #LOGINS
SELECT DISTINCT A.COD_LOGIN,
	A.COD_PES,
	A.LOGIN_LOG,
	UPPER(LTRIM(RTRIM(B.NOME_PES))) AS OPERADOR
INTO #LOGINS
FROM [VCOM].[LOCALCRED_Cobsystems].DBO.LOGIN A
LEFT JOIN [VCOM].[LOCALCRED_Cobsystems].DBO.PESSOAS B ON A.COD_PES = B.COD_PES
WHERE ATIVO_LOG = '1'
AND A.CARGO_LOG NOT IN ('Control Desk','Planejamento/MIS','Gerente','Analista de Processamento','SISTEMA',
'Analista de Sistemas','Analista de Planejamento','Coordenador','COORDENADOR DE COBRANÇA','Analista de MIS',
'ASSISTENTE DE TREINAMENTO E DESENVOLVIMENTO','Monitora de Qualidade','monitoria','supervisor',
'SUPERVISOR DE COBRANÇA',
'Supervisor de Telecom',
'Supervisora','Cliente')
AND A.LOGIN_LOG NOT IN ('ADMIN')


IF OBJECT_ID('TEMPDB..#ACIONAMENTOS') IS NOT NULL DROP TABLE #ACIONAMENTOS
SELECT A.COD_HIST_CLI,
	A.COD_DEV,
	A.COD_OCOR,
	CONVERT(DATE,A.DATA_CAD) AS DATA,
	CONVERT(CHAR,A.DATA_CAD,108) AS HORA,
	A.USUARIO_CAD
INTO #ACIONAMENTOS
FROM [VCOM].[LOCALCRED_Cobsystems].DBO.HISTORICOS_CLIENTES A
INNER JOIN [VCOM].[LOCALCRED_Cobsystems].DBO.OCORRENCIAS_CREDORES B ON A.COD_OCOR = B.COD_OCOR
WHERE CONVERT(DATE,A.DATA_CAD) = CONVERT(DATE, GETDATE()-1, 103)
AND B.COD_CRED BETWEEN '1' AND '11'

SET LANGUAGE 'BRAZILIAN'

IF OBJECT_ID('TEMPDB..#FINAL') IS NOT NULL DROP TABLE #FINAL
SELECT DISTINCT A.*,
	B.OPERADOR,
	UPPER(DATENAME(WEEKDAY,DATA)) AS DIA,
	UPPER(DATENAME(MONTH,DATA)) AS MES,
	YEAR(DATA) AS ANO,
	'1' AS [LOG]
INTO #FINAL
FROM #ACIONAMENTOS A
INNER JOIN #LOGINS B ON A.USUARIO_CAD = B.COD_LOGIN




INSERT INTO ADCOBMIS01.[dbo].[LOGINS_CPY_LOCALCRED]
SELECT DISTINCT 
    A.[DATA],
	A.USUARIO_CAD AS [LOGIN],
	A.OPERADOR AS NOME,
    '' AS TURNO,
	MIN(A.HORA) AS LOGON,
	B.CARTEIRA,
	CASE
	WHEN B.[NOME1] = 'RECUPERADOR (A) DE CREDITO' THEN 'CLT' ELSE 'ESTAGIARIO' END AS TIPO_CARGO,
	A.DIA AS DIA_DA_SEMANA,
	A.MES,
	A.ANO,
	'VCOM' AS ORIGEMDADOS
FROM #FINAL A
INNER JOIN ADCOBMIS01..CPY_RM_GERAL B ON A.OPERADOR = B.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
                         
GROUP BY 
    A.[DATA],
	A.USUARIO_CAD,
	B.CARTEIRA,
		CASE
	WHEN B.[NOME1] = 'RECUPERADOR (A) DE CREDITO' THEN 'CLT' ELSE 'ESTAGIARIO' END,
	A.OPERADOR,
	A.DIA,
	A.MES,
	A.ANO
