
INSERT INTO ADCOBMIS01.[dbo].[LOGINS_CPY_LOCALCRED]
SELECT DISTINCT * FROM (
SELECT distinct
      CONVERT(DATE, A.DATA,103) AS [DATA]
      ,A.CODUSERID AS [LOGIN]
      ,A.NOMUSERID AS NOME
      ,A.TURNO AS TURNO
      ,A.INICIO AS LOGON
	  ,B.CARTEIRA AS CARTEIRA
	  ,CASE
	WHEN B.[NOME1] = 'RECUPERADOR (A) DE CREDITO' THEN 'CLT' ELSE 'ESTAGIARIO' END AS TIPO_CARGO
      ,CASE
		WHEN DATEPART(DW,A.DATA) = 1 THEN 'DOMINGO'
		WHEN DATEPART(DW,A.DATA) = 2 THEN 'SEGUNDA-FEIRA'
		WHEN DATEPART(DW,A.DATA) = 3 THEN 'TERÇA-FEIRA'
		WHEN DATEPART(DW,A.DATA) = 4 THEN 'QUARTA-FEIRA'
		WHEN DATEPART(DW,A.DATA) = 5 THEN 'QUINTA-FEIRA'
		WHEN DATEPART(DW,A.DATA) = 6 THEN 'SEXTA-FEIRA'
		WHEN DATEPART(DW,A.DATA) = 7 THEN 'SÁBADO'
		END AS 'DDS'
	,CASE
		WHEN MONTH(A.DATA)	= 1  THEN 'JANEIRO'
		WHEN MONTH(A.DATA)	= 2  THEN 'FEVEREIRO'
		WHEN MONTH(A.DATA)	= 3  THEN 'MARÇO'
		WHEN MONTH(A.DATA)	= 4  THEN 'ABRIL'
		WHEN MONTH(A.DATA)	= 5  THEN 'MAIO'
		WHEN MONTH(A.DATA)	= 6  THEN 'JUNHO'
		WHEN MONTH(A.DATA)	= 7  THEN 'JULHO'
		WHEN MONTH(A.DATA)	= 8  THEN 'AGOSTO'
		WHEN MONTH(A.DATA)	= 9  THEN 'SETEMBRO'
		WHEN MONTH(A.DATA)	= 10 THEN 'OUTUBRO'
		WHEN MONTH(A.DATA)	= 11 THEN 'NOVEMBRO'
		WHEN MONTH(A.DATA)	= 12 THEN 'DEZEMBRO'
		END AS 'MES'				
,YEAR(A.DATA) AS ANO	
,'ADCOB' AS ORIGEMDADOS
FROM ADCOBDISCADOR.dbo.DL038 A
INNER JOIN ADCOBMIS01..CPY_RM_GERAL B ON A.CODUSERID = B.[LOGIN]
WHERE A.CODUSERID = B.[LOGIN]

AND CONVERT(DATE, A.DATA,103) = '2020-07-04' --= CONVERT(DATE, GETDATE()-1, 103)
AND A.INICIO IS NOT NULL

)GE 
ORDER BY ge.Data, GE.Nome  ASC