
---INSERT INTO ADCOBMIS01.[dbo].[LOGINS_CPY_LOCALCRED]
SELECT 

Q.[DATA],
Q.[LOGIN],
Q.NOME,
Q.TURNO,
Q.LOGON,
Q.CARTEIRA,
Q.TIPO_CARGO,
Q.DDS,
Q.MES,
Q.ANO,
Q.ORIGEMDADOS
 FROM
(
SELECT DISTINCT CONVERT(DATE, LOGIN.[LOGIN], 103) DATA,
						   '' AS [LOGIN],	
                           NAME AS NOME,
                           CASE WHEN MIN(CAST(LOGIN.[LOGIN] AS TIME)) BETWEEN '07:00:00' AND '13:59:59' THEN 'M' ELSE 'T' END AS TURNO,
                           CONVERT(VARCHAR, MIN(LOGIN.[LOGIN]), 108) LOGON,
                           CARTEIRA.CARTEIRA,
						   '' AS TIPO_CARGO
      ,CASE
		WHEN DATEPART(DW,CONVERT(DATE, LOGIN.[LOGIN], 103)) = 1 THEN 'DOMINGO'
		WHEN DATEPART(DW,CONVERT(DATE, LOGIN.[LOGIN], 103)) = 2 THEN 'SEGUNDA-FEIRA'
		WHEN DATEPART(DW,CONVERT(DATE, LOGIN.[LOGIN], 103)) = 3 THEN 'TERÇA-FEIRA'
		WHEN DATEPART(DW,CONVERT(DATE, LOGIN.[LOGIN], 103)) = 4 THEN 'QUARTA-FEIRA'
		WHEN DATEPART(DW,CONVERT(DATE, LOGIN.[LOGIN], 103)) = 5 THEN 'QUINTA-FEIRA'
		WHEN DATEPART(DW,CONVERT(DATE, LOGIN.[LOGIN], 103)) = 6 THEN 'SEXTA-FEIRA'
		WHEN DATEPART(DW,CONVERT(DATE, LOGIN.[LOGIN], 103)) = 7 THEN 'SÁBADO'
		END AS 'DDS'

	,CASE
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 1  THEN 'JANEIRO'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 2  THEN 'FEVEREIRO'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 3  THEN 'MARÇO'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 4  THEN 'ABRIL'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 5  THEN 'MAIO'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 6  THEN 'JUNHO'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 7  THEN 'JULHO'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 8  THEN 'AGOSTO'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 9  THEN 'SETEMBRO'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 10 THEN 'OUTUBRO'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 11 THEN 'NOVEMBRO'
		WHEN MONTH(CONVERT(DATE, LOGIN.[LOGIN], 103))	= 12 THEN 'DEZEMBRO'
		END AS 'MES'				
,YEAR(CONVERT(DATE, LOGIN.[LOGIN], 103)) AS ANO	
,'OLOS' AS ORIGEMDADOS
  FROM [10.155.4.17].[EXPORTDATA].[DBO].[AGENTLOGINDATA] LOGIN
  LEFT JOIN [10.155.4.17].[EXPORTDATA].[DBO].[CONFIGAGENT] AGENT ON AGENT.AGENTID = LOGIN.AGENTID
  LEFT JOIN (
  SELECT 
  CAST(CAST([CALLSTART] AS DATE)AS DATETIME) AS DATA
  ,AGENTID
  ,MIN(CASE WHEN MAILINGNAME LIKE 'AVONFASE1%'  THEN 'AVON FASE_1 '
            WHEN MAILINGNAME LIKE 'AVON_FASE2%' THEN 'AVON FASE_2 '
            WHEN MAILINGNAME LIKE 'PORTOCRED%'  THEN 'Portocred Varejo'
                     ELSE '' END) AS CARTEIRA
FROM [10.155.4.17].[EXPORTDATA].[DBO].[CALLDATA]

WHERE AGENTID IS NOT NULL AND AGENTID > 0
AND MAILINGNAME IS NOT NULL

GROUP BY CAST([CALLSTART] AS DATE), AGENTID) CARTEIRA ON CARTEIRA.AGENTID = LOGIN.AGENTID AND CARTEIRA.DATA = LOGIN.DATA

GROUP BY CONVERT(DATE, LOGIN.[LOGIN], 103),NAME,CARTEIRA.CARTEIRA --CASE WHEN RM.[NOME1] = 'RECUPERADOR (A) DE CREDITO' THEN 'CLT' ELSE 'ESTAGIARIO' END

)Q
WHERE Q.[DATA] = CONVERT(DATE, GETDATE()-1, 103)