SELECT
A.DATA_BASE,
A.ID_CLIENTE,
A.RA,
A.NOME,
CASE WHEN MAX(A.DT_VENCIMENTO) IS NULL THEN convert(varchar, MAX(B.DT_VENCIMENTO), 103) ELSE MAX(A.DT_VENCIMENTO) END AS VENCIMENTO,
CASE WHEN CONVERT(VARCHAR, A.DT_INCLUSAO,103) IS NULL THEN CONVERT(VARCHAR, MAX(B.DT_INCLUSAO),103) ELSE CONVERT(VARCHAR, A.DT_INCLUSAO,103) END AS DT_INCLUSAO,
CASE WHEN A.VL_SALDO IS NULL THEN E.VL_PARCELA ELSE A.VL_SALDO END AS VL_SALDO


FROM LOCALCOB_DW..CARTEIRA_AVON_V3 A
LEFT JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_ACORDO_DIVIDA] B ON A.ID_CLIENTE = B.ID_CLIENTE
LEFT JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].TB_CARGA_DIVIDA_BATIMENTO D ON A.RA = D.NM_CLIENTE_CEDENTE
LEFT JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].TB_FATURA E ON A.ID_CLIENTE = E.ID_CLIENTE AND E.DT_PARCELA = (SELECT MAX(T.DT_PARCELA) FROM [10.155.4.158].[EASYCOLLECTOR].[DBO].TB_FATURA T WHERE T.ID_CLIENTE = A.ID_CLIENTE)
WHERE A.DATA_BASE = '2020-08-11'
AND A.FASE_COB = 'FASE1'
--AND A.[ACORDO ATIVO] = 'SIM'
 /* SEM VENCIMENTO*/
 AND A.RA = 64841844

GROUP BY
A.ID_CLIENTE,
A.RA,
A.DATA_BASE,
A.NOME,
A.DT_INCLUSAO,
A.VL_SALDO,
E.VL_PARCELA


--SELECT * FROM [10.155.4.158].[EASYCOLLECTOR].[DBO].TB_FATURA
--WHERE ID_CLIENTE = '1053'

--SELECT * FROM LOCALCOB_DW..CARTEIRA_AVON_V3
--WHERE RA = 77254961


--SELECT DATA_BASE, ID_CLIENTE, RA, CPF, CONTRATO, ID_CONTRATO INTO LOCALCOB_DW..CARTEIRA_AVON_V3T FROM LOCALCOB_DW..CARTEIRA_AVON_V3

--SELECT    * FROM /*PRINCIPAL*/	[10.155.4.158].[EASYCOLLECTOR].[dbo].TB_CLIENTE CLI
--LEFT JOIN  /*CONTRATO*/			[10.155.4.158].[EASYCOLLECTOR].[dbo].TB_CONTRATO CONT ON CONT.ID_CLIENTE = CLI.ID_CLIENTE
--INNER JOIN /*DIVIDA*/			[10.155.4.158].[EASYCOLLECTOR].[dbo].TB_DIVIDA DIV ON DIV.ID_CONTRATO = CONT.ID_CONTRATO
--LEFT JOIN  /*DET. DIVIDA*/		[10.155.4.158].[EASYCOLLECTOR].[dbo].TB_DIVIDA_DETALHE DIVD ON DIVD.ID_CONTRATO = CONT.ID_CONTRATO