IF OBJECT_ID('TEMPDB..#VENCIMENTO') IS NOT NULL DROP TABLE #VENCIMENTO
SELECT DISTINCT A.COD_TIT AS COD_TIT,
	A.CONTRATO_TIT AS CONTRATO_TIT,
	MIN(B.VCTO_PARC) AS MENOR_VENCIMENTO,
	COUNT(DISTINCT B.NUMERO_PARC) AS QTD_PARC
INTO #VENCIMENTO
FROM [LOCALCRED_Cobsystems].[DBO].TITULOS A
LEFT JOIN [LOCALCRED_Cobsystems].[DBO].PARCELAS B ON A.COD_TIT = B.COD_TIT
WHERE A.COD_CRED  = 12
AND B.NUMERO_PARC = 1
GROUP BY A.COD_TIT,
	A.CONTRATO_TIT
	

IF OBJECT_ID('TEMPDB..#BASE') IS NOT NULL DROP TABLE #BASE

DECLARE @INICIO DATE
DECLARE @FIM DATE
SET @INICIO = '2020-10-01' --DATEADD(MM,0,DATEADD(DD,-DAY(GETDATE())+1,(SUBSTRING(CONVERT(VARCHAR,(GETDATE()),120),1,10)) + '' 00:00:00''))
SET @FIM = '2020-10-31' --DATEADD(MM,1,DATEADD(DD,-DAY(GETDATE()),(SUBSTRING(CONVERT(VARCHAR,(GETDATE()),120),1,10)) + '' 23:59:59''))

SELECT DISTINCT D.COD_PARC,
	B.COD_TIT,
	A.COD_REC,
	A.CONTRATO_TIT,
	B.COD_FILI,
	LTRIM(RTRIM(A.CPFCGC_PES)) AS CPF,
	CONVERT(DATE,E.DATADOCUMENTO) AS DATA_ACORDO,
	CONVERT(DATE,A.VCTO_PARC) AS DATA_VENCIMENTO,
	CONVERT(DATE,A.DT_PGTO_REC) AS DATA_PAGAMENTO,
	A.NUMERO_PARC AS PARCELA_PAGA,
	A.PLANO_TIT AS PLANO,
	CONVERT(MONEY,A.VR_ORIG_PARC) AS VALOR_PARCELA,
	CONVERT(MONEY,A.VALOR_TOTAL_REC) AS VALOR_PAGO,	LTRIM(RTRIM(A.NOME_DEV)) AS CLIENTE,
	LTRIM(RTRIM(G.NOME_PES)) AS OPERADOR,
	LTRIM(RTRIM(H.NOME_CEDENTE)) AS SEGMENTAÇÃO
	INTO #BASE
FROM      [LOCALCRED_Cobsystems].[DBO].V_RECIBO A
LEFT JOIN [LOCALCRED_Cobsystems].[DBO].TITULOS B ON A.CONTRATO_TIT = B.CONTRATO_TIT
LEFT JOIN [LOCALCRED_Cobsystems].[DBO].RECEBIMENTOS C ON A.COD_REC = C.COD_REC  AND B.COD_TIT = C.COD_TIT 
LEFT JOIN [LOCALCRED_Cobsystems].[DBO].PARCELAS D ON B.COD_TIT = D.COD_TIT AND A.NUMERO_PARC = D.NUMERO_PARC AND A.VR_ORIG_PARC = D.VR_ORIG_PARC
LEFT JOIN [LOCALCRED_Cobsystems].[DBO].BOLETOS_EM E ON C.COD_BEM = E.COD_BEM AND B.COD_TIT = E.COD_TIT
LEFT JOIN [LOCALCRED_Cobsystems].[DBO].LOGIN F ON E.USUARIO_CAD = F.COD_LOGIN 
LEFT JOIN [LOCALCRED_Cobsystems].[DBO].PESSOAS G ON F.COD_PES = G.COD_PES
LEFT JOIN [LOCALCRED_Cobsystems].[DBO].AUX_CREDZ H ON A.CONTRATO_TIT = H.ID_CLIENTE
WHERE B.COD_CRED = 12



AND CONVERT(DATE,A.DT_PGTO_REC) BETWEEN @INICIO AND @FIM

IF OBJECT_ID('TEMPDB..#PAGAMENTOS') IS NOT NULL DROP TABLE #PAGAMENTOS
SELECT DISTINCT A.*,
	DATEDIFF(DAY,B.MENOR_VENCIMENTO,A.DATA_PAGAMENTO) AS ATRASO_PAGAMENTO
INTO #PAGAMENTOS
FROM #BASE A
LEFT JOIN #VENCIMENTO B ON A.COD_TIT = B.COD_TIT AND A.CONTRATO_TIT = B.CONTRATO_TIT


SET LANGUAGE 'BRAZILIAN'

IF OBJECT_ID('TEMPDB..#PAGAMENTOS2') IS NOT NULL DROP TABLE #PAGAMENTOS2
SELECT DISTINCT A.*,
CASE
	WHEN A.PARCELA_PAGA = 1 AND PLANO = 1 THEN 'PAGAMENTO A VISTA'
	ELSE 'PAGAMENTO PARCELADO'
END TIPO_PAGAMENTO,
CASE
	WHEN A.PARCELA_PAGA = 1 THEN 'PRIMEIRA PARCELA'
	ELSE 'COLCHÃO'
END TIPO_PAGAMENTO_PARCELA,
	REPLACE((CONVERT(VARCHAR,ROUND(((CONVERT(FLOAT,PARCELA_PAGA)/CONVERT(FLOAT,PLANO))*100),2)) + ' %'),'.',',') "% PLANO PAGO",
	YEAR(DATA_PAGAMENTO) AS ANO_PGTO,
	(CONVERT(VARCHAR,MONTH(DATA_PAGAMENTO)) + '. ' + UPPER(DATENAME(MONTH,DATA_PAGAMENTO))) AS MES_PGTO
INTO #PAGAMENTOS2
FROM(
SELECT DISTINCT A.*,
	'ESTRE' AS CARTEIRA,
	'' AS FAIXA_ATRASO
FROM #PAGAMENTOS A
LEFT JOIN [LOCALCRED_Cobsystems].[DBO].AUX_CREDZ B ON A.CONTRATO_TIT = B.ID_CLIENTE)A
ORDER BY A.CONTRATO_TIT


IF OBJECT_ID('TEMPDB..#BASE_PC_ESTRE') IS NOT NULL DROP TABLE #BASE_PC_ESTRE


SELECT DISTINCT CONVERT(VARCHAR(MAX),COD_PARC) AS COD_PARC,
	CONVERT(VARCHAR(MAX),COD_TIT) AS COD_TIT,
	CONVERT(VARCHAR(MAX),COD_REC) AS COD_REC,
	CONVERT(VARCHAR(MAX),CONTRATO_TIT) AS CONTRATO_TIT,
	CONVERT(VARCHAR(MAX),CPF) AS CPF,
	CONVERT(DATE,DATA_ACORDO) AS DATA_ACORDO,
	CONVERT(DATE,DATA_VENCIMENTO) AS DATA_VENCIMENTO,
	CONVERT(DATE,DATA_PAGAMENTO) AS DATA_PAGAMENTO,
	CONVERT(INT,PARCELA_PAGA) AS PARCELA_PAGA,
	CONVERT(INT,PLANO) AS PLANO,
	CONVERT(MONEY,VALOR_PARCELA) AS VALOR_PARCELA,
	CONVERT(MONEY,VALOR_PAGO) AS VALOR_PAGO,
	CONVERT(VARCHAR(MAX),CLIENTE) AS CLIENTE,
	CONVERT(VARCHAR(MAX),OPERADOR) AS OPERADOR,
	CONVERT(VARCHAR(MAX),SEGMENTAÇÃO) AS SEGMENTAÇÃO,
	CONVERT(INT,ATRASO_PAGAMENTO) AS ATRASO_PAGAMENTO,
	CONVERT(VARCHAR(MAX),CARTEIRA) AS CARTEIRA,
	CONVERT(VARCHAR(MAX),FAIXA_ATRASO) AS FAIXA_ATRASO,
	CONVERT(VARCHAR(MAX),TIPO_PAGAMENTO) AS TIPO_PAGAMENTO,
	CONVERT(VARCHAR(MAX),TIPO_PAGAMENTO_PARCELA) AS TIPO_PAGAMENTO_PARCELA,
	CONVERT(VARCHAR(MAX),[% PLANO PAGO]) AS [% PLANO PAGO],
	CONVERT(VARCHAR(MAX),ANO_PGTO) AS ANO_PGTO,
	CONVERT(VARCHAR(MAX),MES_PGTO) AS MES_PGTO,
	B.NOME_FILI




INTO #BASE_PC_ESTRE
FROM #PAGAMENTOS2 A
LEFT JOIN [LOCALCRED_Cobsystems].[DBO].filiais B on A.COD_FILI =  B.codigo_fili

SELECT
LEFT(CONTRATO_TIT,8) AS COD_CONTA,
CONTRATO_TIT,
CPF,
DATA_ACORDO,
DATA_PAGAMENTO,
VALOR_PAGO,
CLIENTE,
CASE
	WHEN OPERADOR IS NULL THEN 'INDIRETO' ELSE OPERADOR END AS OPERADOR,
ATRASO_PAGAMENTO,
NOME_FILI,
CASE					
	WHEN  NOME_FILI	=	1500	THEN	'AMBIENTAL SUL'
	WHEN  NOME_FILI	=	1400	THEN	'CAVO SERVICOS E SANEAMENTO S/A'
	WHEN  NOME_FILI	=	2500	THEN	'CGR GUATAPARA CENTRO DE GER. RESID.LTDA'
	WHEN  NOME_FILI	=	1700	THEN	'CTR ITABORAI '
	WHEN  NOME_FILI	=	1000	THEN	'ESTRE AMBIENTAL SA '
	WHEN  NOME_FILI	=	2400	THEN	'ESTRE SPI AMBIENTAL SA'
	WHEN  NOME_FILI	=	1900	THEN	'GEO VISION SOLUCOES AMB.E ENERGIA S/A'
	WHEN  NOME_FILI	=	2000	THEN	'NGA JARDINOPOLIS NUCLEO DE GER. AMB.LTDA'
	WHEN  NOME_FILI	=	1600	THEN	'NGA NUCLEO DE GER. AMB.LTDA'
	WHEN  NOME_FILI	=	1100	THEN	'NGA RIBEIRAO PRETO NUCLEO DE GER. AMB.LTDA'
	WHEN  NOME_FILI	=	1200	THEN	'OXIL MANUFATURA VER.E GER.DE RESIDUOS LTDA'
	WHEN  NOME_FILI	=	2100	THEN	'RECICLAX RECICLAGEM RESID.CONSTR.CIVIL LTDA'
	WHEN  NOME_FILI	=	1300	THEN	'RESICONTROL SOLUCOES AMBIENTAIS S/A'
	WHEN  NOME_FILI	=	1300	THEN	'RESICONTROL SOLUCOES AMBIENTAIS S/A'
	WHEN  NOME_FILI	=	1300	THEN	'RESICONTROL SOLUCOES AMBIENTAIS S/A'
	WHEN  NOME_FILI	=	2300	THEN	'V2 AMBIENTAL SPE S/A'
	WHEN  NOME_FILI	=	2200	THEN	'VIVA AMBIENTAL E SERVICOS S/A'
	ELSE ''	END AS 	EMPRESA		,
					
CASE					
	WHEN  NOME_FILI	=	1500	THEN	'08.738.827/0001-09'
	WHEN  NOME_FILI	=	1400	THEN	'01.030.942/0001-85'
	WHEN  NOME_FILI	=	2500	THEN	'08.463.831/0001-01'
	WHEN  NOME_FILI	=	1700	THEN	'09.014.794/0001-17 '
	WHEN  NOME_FILI	=	1000	THEN	'03.147.393/0001-59'
	WHEN  NOME_FILI	=	2400	THEN	'10.541.089/0001-57'
	WHEN  NOME_FILI	=	1900	THEN	'08.303.561/0002-52'
	WHEN  NOME_FILI	=	2000	THEN	'10.556.415/0001-08'
	WHEN  NOME_FILI	=	1600	THEN	'09.325.263/0001-45'
	WHEN  NOME_FILI	=	1100	THEN	'10.536.788/0001-09'
	WHEN  NOME_FILI	=	1200	THEN	'03.506.999/0001-33'
	WHEN  NOME_FILI	=	2100	THEN	'09.612.814/0001-51'
	WHEN  NOME_FILI	=	1300	THEN	'00.957.744/0001-07'
	WHEN  NOME_FILI	=	1300	THEN	'00.957.744/0004-41'
	WHEN  NOME_FILI	=	1300	THEN	'00.957.744/0002-52'
	WHEN  NOME_FILI	=	2300	THEN	'10.826.008/0001-65'
	WHEN  NOME_FILI	=	2200	THEN	'05.566.002/0001-66'
	ELSE ''	END AS 	CNPJ	,	
					
CASE					
	WHEN  NOME_FILI	=	1500	THEN	'341'
	WHEN  NOME_FILI	=	1400	THEN	'341'
	WHEN  NOME_FILI	=	2500	THEN	'341'
	WHEN  NOME_FILI	=	1700	THEN	'341'
	WHEN  NOME_FILI	=	1000	THEN	'341'
	WHEN  NOME_FILI	=	2400	THEN	'341'
	WHEN  NOME_FILI	=	1900	THEN	'341'
	WHEN  NOME_FILI	=	2000	THEN	'341'
	WHEN  NOME_FILI	=	1600	THEN	'341'
	WHEN  NOME_FILI	=	1100	THEN	'341'
	WHEN  NOME_FILI	=	1200	THEN	'341'
	WHEN  NOME_FILI	=	2100	THEN	'341'
	WHEN  NOME_FILI	=	1300	THEN	'341'
	WHEN  NOME_FILI	=	1300	THEN	'341'
	WHEN  NOME_FILI	=	1300	THEN	'341'
	WHEN  NOME_FILI	=	2300	THEN	'341'
	WHEN  NOME_FILI	=	2200	THEN	'341'
	ELSE ''	END AS 	BANCO	,	
					
CASE					
	WHEN  NOME_FILI	=	1500	THEN	'910'
	WHEN  NOME_FILI	=	1400	THEN	'912'
	WHEN  NOME_FILI	=	2500	THEN	'623'
	WHEN  NOME_FILI	=	1700	THEN	'910'
	WHEN  NOME_FILI	=	1000	THEN	'910'
	WHEN  NOME_FILI	=	2400	THEN	'623'
	WHEN  NOME_FILI	=	1900	THEN	'623'
	WHEN  NOME_FILI	=	2000	THEN	'623'
	WHEN  NOME_FILI	=	1600	THEN	'623'
	WHEN  NOME_FILI	=	1100	THEN	'623'
	WHEN  NOME_FILI	=	1200	THEN	'1652'
	WHEN  NOME_FILI	=	2100	THEN	'623'
	WHEN  NOME_FILI	=	1300	THEN	'910'
	WHEN  NOME_FILI	=	1300	THEN	'76'
	WHEN  NOME_FILI	=	1300	THEN	'910'
	WHEN  NOME_FILI	=	2300	THEN	'910'
	WHEN  NOME_FILI	=	2200	THEN	'262'
	ELSE ''	END AS 	AGENCIA		,
					
CASE					
	WHEN  NOME_FILI	=	1500	THEN	'02510-5'
	WHEN  NOME_FILI	=	1400	THEN	'09593-2'
	WHEN  NOME_FILI	=	2500	THEN	'54266-9'
	WHEN  NOME_FILI	=	1700	THEN	'02511-3'
	WHEN  NOME_FILI	=	1000	THEN	'10052-8'
	WHEN  NOME_FILI	=	2400	THEN	'64097-6'
	WHEN  NOME_FILI	=	1900	THEN	'63838-4'
	WHEN  NOME_FILI	=	2000	THEN	'63836-8'
	WHEN  NOME_FILI	=	1600	THEN	'63834-3'
	WHEN  NOME_FILI	=	1100	THEN	'63830-1'
	WHEN  NOME_FILI	=	1200	THEN	'11313-3'
	WHEN  NOME_FILI	=	2100	THEN	'65570-1'
	WHEN  NOME_FILI	=	1300	THEN	'10223-5'
	WHEN  NOME_FILI	=	1300	THEN	'21028-5'
	WHEN  NOME_FILI	=	1300	THEN	'11085-7'
	WHEN  NOME_FILI	=	2300	THEN	'02049-4'
	WHEN  NOME_FILI	=	2200	THEN	'17752-0'
	ELSE ''	END AS 	CONTA		
from #BASE_PC_ESTRE 

ORDER BY 1 ASC