SELECT DISTINCT
A.COD_TIT,
A.CONTRATO_TIT,
A.CPF,
A.DEVEDOR,
MAX(A.ATRASO) AS ATRASO,
A.VALOR,
A.UF,
B.DATA_ACORDO,
B.DATA_VENCIMENTO,
B.DATA_PAGAMENTO,
B.PARCELA_PAGA,
B.PLANO,
B.VALOR_PARCELA,
B.VALOR_PAGO,
B.OPERADOR,
B.ATRASO_PAGAMENTO,
B.TIPO_PAGAMENTO,
B.TIPO_PAGAMENTO_PARCELA,
B.[% PLANO PAGO]

FROM ADCOBMIS01..FOTOGRAFIA_VCOM A
LEFT JOIN ADCOBMIS01..PAGAMENTOS_VCOM B ON A.COD_TIT = B.COD_TIT
WHERE A.DATA BETWEEN '2020-09-01' AND '2020-09-15'
AND B.DATA_PAGAMENTO BETWEEN '2020-09-01' AND '2020-09-15'
AND A.COD_CRED = 6
AND B.CARTEIRA = 'VAICAR'

GROUP BY 

A.COD_TIT,
A.CONTRATO_TIT,
A.CPF,
A.DEVEDOR,
A.VALOR,
A.UF,
B.DATA_ACORDO,
B.DATA_VENCIMENTO,
B.DATA_PAGAMENTO,
B.PARCELA_PAGA,
B.PLANO,
B.VALOR_PARCELA,
B.VALOR_PAGO,
B.OPERADOR,
B.ATRASO_PAGAMENTO,
B.TIPO_PAGAMENTO,
B.TIPO_PAGAMENTO_PARCELA,
B.[% PLANO PAGO]
ORDER BY 4 ASC