SELECT DISTINCT *  FROM (
SELECT DISTINCT
AP.NU_NOSSO_NUMERO AS NOSSONUMERO,
--A.ID_CLIENTE,
A.ID_ACORDO,
C.NM_NOME,
--B.NM_DIVIDA_CEDENTE AS CONTRATO,
C.NM_CLIENTE_CEDENTE AS RA,
LEFT(CONVERT(VARCHAR,DT_ACORDO,108),2) AS HORA,
CASE
	WHEN LEFT(CONVERT(VARCHAR,DT_ACORDO,108),2) < 14 THEN 'MANHÃ' ELSE 'TARDE' END AS PERIODO,
--RIGHT(A.NM_ACORDO_CEDENTE, 7) AS BLNUMACORDO,
CONVERT(DATE, A.DT_ACORDO, 103) AS DATA_ACORDO,
CONVERT(DATE, F.DT_PARCELA ,103) AS VENCIMENTO,
CONVERT(DATE, A.DT_CANCELAMENTO, 103) AS DT_CANCELAMENTO,
CONVERT(DATE,AP.DT_PAGAMENTO,103) AS DT_PAGAMENTO, 
CASE WHEN G.NM_USUARIO IS NULL THEN 'INDIRETO' ELSE 'DIRETO' END  DIR_IND,
    SUM(CAST(F.VL_PARCELA AS MONEY)) AS VL_PARCELA, 
    SUM(CAST(AP.VL_RECEITA AS MONEY)) AS VL_RECEITA,
A.ID_USUARIO,
A.NU_PLANO,
RTRIM(LTRIM(LEFT(RTRIM(LTRIM(LEFT(G.NM_USUARIO,CHARINDEX(' ',G.NM_USUARIO )+1))),12)))+'.'  AS PRI_NOME_OP,
--NU_CPF_CNPJ AS CPF,
LTRIM(RTRIM(CASE WHEN G.NM_USUARIO IS NULL THEN 'INDIRETO' ELSE G.NM_USUARIO END)) AS OPERADOR,
CASE F.NU_PARCELA WHEN 1 THEN 'NN' ELSE 'COLCHÃO' END AS TIPO,
FASE.NM_DETALHE_VALOR AS FASE,
CAST(F.NU_PARCELA AS VARCHAR)+'/'+CAST(A.NU_PLANO AS VARCHAR) PARCELAS,

CASE FASE.NM_DETALHE_VALOR WHEN '002' THEN
CASE 
	 WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) < 5					THEN 'A - F1 - <05'
	 WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN  8 AND 15		THEN 'B - F1 - 08 A 15'
	 WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 16 AND 30		THEN 'C - F1 - 16 A 30'
	 WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 31 AND 60		THEN 'D - F1 - 31 A 60'
	 WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 61 AND 90		THEN 'E - F1 - 61 A 90'
	 WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 5 AND 7		THEN 'F - F1 - 05 A 07'
	 WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) >90					THEN 'G - F1 - >90'
	 ELSE 'FASE 1 - FORA DA FAIXA'
	 END
WHEN '506' THEN
CASE WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN     91 AND 180		THEN 'A - F2'
	 WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN     181 AND 360	THEN 'B - F3'
	 WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN     361 AND 1080	THEN 'C - F4'
	 WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) > 1081						THEN 'D - F5'
	 ELSE 'FASE 2 - FORA DA FAIXA'
	 END
END AS PERFORMANTE,

CASE
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) <				5			THEN 	'A - <5 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	5	 AND	7		THEN 	'B - 5 a 7 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	8	 AND	15		THEN 	'C - 8 a 15 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	16	 AND	30		THEN 	'D - 16 a 30 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	31	 AND	60		THEN 	'E - 31 a 60 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	61	 AND	69		THEN 	'F - 61 a 69 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	70	 AND	90		THEN 	'G - 70 a 90 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	91	 AND	180		THEN 	'H - 91 a 180 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	181	 AND	270		THEN 	'I - 181 a 270 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	271	 AND	360		THEN 	'J - 271 a 360 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	361	 AND	720		THEN 	'K - 361 a 720 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	721	 AND	1080	THEN 	'L - 721 a 1080 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	1081 AND	1440	THEN 	'M - 1081 a 1440 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	1441 AND	1800	THEN 	'N - 1441 a 1800 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	1801 AND	2160	THEN 	'O - 1801 a 2160 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	2161 AND	2520	THEN 	'P - 2161 a 2520 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	2521 AND	2880	THEN 	'Q - 2521 a 2880 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	2881 AND	3240	THEN 	'R - 2881 a 3240 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN	3241 AND	3600	THEN 	'S - 3241 a 3600 dias'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO)					   >3600	THEN 	'T - Acima 3600 dias' END AS FX_ATRASO,
CASE 
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) < 5					THEN 'A - Menor 5'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 5 AND 7		THEN 'B - 5 a 7'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 8 AND 30	THEN 'C - 8 a 30'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 31 AND 60	THEN 'D - 31 a 60'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 61 AND 90	THEN 'E - 61 a 90'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) > 90				THEN 'F - Maior 90' END AS AGING_CLUSTER,
CASE 
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) < 8					THEN 'A - 08<'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 8 AND 30	THEN 'B - 08 a 30'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 31 AND 60	THEN 'C - 31 a 60'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 61 AND 90	THEN 'D - 61 a 90'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) > 90				THEN 'E - 90<' END AS AGING_CLUSTER_2,
	CASE 
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 0 AND 180	 THEN 'FASE 2 - 0 a 180'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 181 AND 360	 THEN 'FASE 3 - 181 a 360'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) BETWEEN 361 AND 1080 THEN 'FASE 4 - 361 a 1080'
	WHEN DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO) > 1081				 THEN 'FASE 5 - 1081 >' END AS AGING_CLUSTER_3,

CASE WHEN AP.TP_STATUS_ANTERIOR = 0 THEN 
(CASE WHEN A.TP_STATUS = 3 THEN 
(CASE WHEN CONVERT(DATE,A.DT_CANCELAMENTO, 103) > CONVERT(DATE, A.DT_ACORDO, 103) THEN 0
	 ELSE (CASE WHEN CONVERT(DATE, A.DT_CANCELAMENTO, 103) = CONVERT(DATE, A.DT_ACORDO, 103) THEN 3 ELSE 0 END) END) ELSE 0 END)
	 WHEN A.TP_STATUS = 0 THEN 0
	 WHEN A.TP_STATUS = 1 THEN 1
	 WHEN A.TP_STATUS = 2 THEN 2 END AS STATUS_PROMESSA,
	 MONTH(F.DT_PARCELA) AS MES_NUMBER,
CASE
	WHEN MONTH(F.DT_PARCELA)	= 1  THEN 'JANEIRO'
	WHEN MONTH(F.DT_PARCELA)	= 2  THEN 'FEVEREIRO'
	WHEN MONTH(F.DT_PARCELA)	= 3  THEN 'MARÇO'
	WHEN MONTH(F.DT_PARCELA)	= 4  THEN 'ABRIL'
	WHEN MONTH(F.DT_PARCELA)	= 5  THEN 'MAIO'
	WHEN MONTH(F.DT_PARCELA)	= 6  THEN 'JUNHO'
	WHEN MONTH(F.DT_PARCELA)	= 7  THEN 'JULHO'
	WHEN MONTH(F.DT_PARCELA)	= 8  THEN 'AGOSTO'
	WHEN MONTH(F.DT_PARCELA)	= 9  THEN 'SETEMBRO'
	WHEN MONTH(F.DT_PARCELA)	= 10 THEN 'OUTUBRO'
	WHEN MONTH(F.DT_PARCELA)	= 11 THEN 'NOVEMBRO'
	WHEN MONTH(F.DT_PARCELA)	= 12 THEN 'DEZEMBRO'
		END AS 'MES',
YEAR(F.DT_PARCELA) AS ANO
--DATEDIFF(D,MIN(B.DT_VENCIMENTO),DT_ACORDO)  AS ATRASO
--MIN(CONVERT(DATE,B.DT_VENCIMENTO, 103)) AS VENCIMENTO_ORIGINAL,
--MIN(CONVERT(DATE,B.DT_INCLUSAO, 103)) AS DATA_REMESSA,

--MIN(CONVERT(DATE,AP.DT_FATURA, 103)) AS DATA_FATURAMENTO

FROM      TB_ACORDO A
LEFT JOIN TB_ACORDO_DIVIDA B  WITH (NOLOCK) ON B.ID_ACORDO = A.ID_ACORDO
LEFT JOIN TB_ACORDO_PARCELA F WITH(NOLOCK)	ON F.ID_ACORDO				= A.ID_ACORDO
LEFT JOIN TB_ACORDO_DIVIDA_DETALHE FASE		ON FASE.ID_ACORDO			= A.ID_ACORDO
LEFT JOIN TB_USUARIO G WITH (NOLOCK) ON G.ID_USUARIO = A.ID_USUARIO
LEFT JOIN TB_CLIENTE C        WITH (NOLOCK) ON C.ID_CLIENTE = B.ID_CLIENTE
LEFT JOIN TB_FATURA AP ON A.ID_CLIENTE = AP.ID_CLIENTE AND A.ID_ACORDO	= AP.ID_ACORDO AND AP.DT_FATURA = F.DT_PARCELA
WHERE FASE.ID_DETALHE IN ('351')

GROUP BY
AP.NU_NOSSO_NUMERO,
DT_ACORDO,
--B.NM_DIVIDA_CEDENTE,
--A.ID_CLIENTE,
C.NM_CLIENTE_CEDENTE,
A.ID_ACORDO,
C.NM_NOME,
b.NM_DIVIDA_CEDENTE,
CONVERT(VARCHAR,DT_ACORDO,108),
LEFT(CONVERT(VARCHAR,DT_ACORDO,108),2),
CASE
	WHEN LEFT(CONVERT(VARCHAR,DT_ACORDO,108),2) < 14 THEN 'MANHÃ' ELSE 'TARDE' END,
--RIGHT(A.NM_ACORDO_CEDENTE, 7),
CONVERT(DATE, A.DT_ACORDO, 103),
CONVERT(DATE, F.DT_PARCELA ,103),
CONVERT(DATE, A.DT_CANCELAMENTO, 103),
CONVERT(DATE,AP.DT_PAGAMENTO,103),
RTRIM(LTRIM(LEFT(RTRIM(LTRIM(LEFT(G.NM_USUARIO,CHARINDEX(' ',G.NM_USUARIO )+1))),12)))+'.',
CASE WHEN G.NM_USUARIO IS NULL THEN 'INDIRETO' ELSE 'DIRETO' END  ,
--NU_CPF_CNPJ,
LTRIM(RTRIM(CASE WHEN G.NM_USUARIO IS NULL THEN 'INDIRETO' ELSE G.NM_USUARIO END)),
    CAST(F.VL_PARCELA AS MONEY), 
    CAST(AP.VL_RECEITA AS MONEY),

A.ID_USUARIO,
A.NU_PLANO,
CASE F.NU_PARCELA WHEN 1 THEN 'NN' ELSE 'COLCHÃO' END,
FASE.NM_DETALHE_VALOR,
CAST(F.NU_PARCELA AS VARCHAR)+'/'+CAST(A.NU_PLANO AS VARCHAR),

CASE WHEN AP.TP_STATUS_ANTERIOR = 0 THEN 
(CASE WHEN A.TP_STATUS = 3 THEN 
(CASE WHEN CONVERT(DATE,A.DT_CANCELAMENTO, 103) > CONVERT(DATE, A.DT_ACORDO, 103) THEN 0
	 ELSE (CASE WHEN CONVERT(DATE, A.DT_CANCELAMENTO, 103) = CONVERT(DATE, A.DT_ACORDO, 103) THEN 3 ELSE 0 END) END) ELSE 0 END)
	 WHEN A.TP_STATUS = 0 THEN 0
	 WHEN A.TP_STATUS = 1 THEN 1
	 WHEN A.TP_STATUS = 2 THEN 2 END,
	 MONTH(F.DT_PARCELA),
CASE
	WHEN MONTH(F.DT_PARCELA)	= 1  THEN 'JANEIRO'
	WHEN MONTH(F.DT_PARCELA)	= 2  THEN 'FEVEREIRO'
	WHEN MONTH(F.DT_PARCELA)	= 3  THEN 'MARÇO'
	WHEN MONTH(F.DT_PARCELA)	= 4  THEN 'ABRIL'
	WHEN MONTH(F.DT_PARCELA)	= 5  THEN 'MAIO'
	WHEN MONTH(F.DT_PARCELA)	= 6  THEN 'JUNHO'
	WHEN MONTH(F.DT_PARCELA)	= 7  THEN 'JULHO'
	WHEN MONTH(F.DT_PARCELA)	= 8  THEN 'AGOSTO'
	WHEN MONTH(F.DT_PARCELA)	= 9  THEN 'SETEMBRO'
	WHEN MONTH(F.DT_PARCELA)	= 10 THEN 'OUTUBRO'
	WHEN MONTH(F.DT_PARCELA)	= 11 THEN 'NOVEMBRO'
	WHEN MONTH(F.DT_PARCELA)	= 12 THEN 'DEZEMBRO'
	     END ,
YEAR(F.DT_PARCELA)

)FORA
WHERE CONVERT(DATE, FORA.DT_PAGAMENTO, 103) BETWEEN '2020-07-01' AND '2020-07-31'  --DATEADD(MM,0,DATEADD(DD,-DAY(GETDATE())+1,(SUBSTRING(CONVERT(VARCHAR,(GETDATE()),120),1,10)) + ' 00:00:00')) AND DATEADD(MM,1,DATEADD(DD,-DAY(GETDATE()),(SUBSTRING(CONVERT(VARCHAR,(GETDATE()),120),1,10)) + ' 23:59:59'))
AND FORA.DT_PAGAMENTO IS NOT NULL
AND FORA.FASE = 506