IF OBJECT_ID('tempdb..##QUERY1') IS NOT NULL DROP TABLE ##QUERY1
IF OBJECT_ID('tempdb..##MAXQUERY2') IS NOT NULL DROP TABLE ##MAXQUERY2
IF OBJECT_ID('tempdb..##MAXQUERY3') IS NOT NULL DROP TABLE ##MAXQUERY3
SELECT
CONVERT(DATE, [DATA ENTRADA],103) AS DATA_ENTRADA
,CONTRATO
,DATA_VENCIMENTO
,[VALOR COBRANÇA] AS VALOR_COBRANCA
,[VALOR COBRANÇA1] AS VALOR_COBRANCA1
,DATA_VENCIMENTO1
,VENCIMENTO
,SAFRA
,CONVERT(DATE, LOTE, 103) AS LOTE
--,(RTRIM(REPLICATE('0', 2 - LEN(CAST(DATEPART(DAY,LOTE) AS VARCHAR)))) + CAST(DATEPART(DAY,LOTE) AS VARCHAR)+'/'+ 
--RTRIM(REPLICATE('0', 2 - LEN(CAST(DATEPART(MONTH,LOTE) AS VARCHAR)))) + CAST(DATEPART(MONTH,LOTE) AS VARCHAR)+'/'+
--CAST(DATEPART(YEAR,LOTE) AS VARCHAR)) AS LOTE
,[LOTE P] AS LOTEP
,Obs AS OBS
,VALIDADOR
,PGTO
,[VLR PGTO] AS DATA_PGTO
,[ATRASO PGTO] AS ATRASO_PGTO
,MÊS AS MES
,ANO AS ANO

INTO ##QUERY1
FROM ADCOBMIS01..BASE_SAFRADA_AVON


SELECT 
LOTE
	,CASE
	WHEN LOTEP = 30 THEN CAST(SUM(VALOR_COBRANCA1) AS MONEY) ELSE '' END AS 'SAFRA_30'
	,CASE
	WHEN LOTEP = 60 THEN CAST(SUM(VALOR_COBRANCA1) AS MONEY) ELSE '' END AS 'SAFRA_60'
	,CASE
	WHEN LOTEP = 90 THEN CAST(SUM(VALOR_COBRANCA1) AS MONEY) ELSE '' END AS 'SAFRA_90'
	--,CASE
	--WHEN ATRASO_PGTO BETWEEN 5 AND 30  THEN CAST(SUM(PGTO) AS MONEY) ELSE '' END AS 'SAFRA_30_PG'
	--,CASE
	--WHEN ATRASO_PGTO BETWEEN 31 AND 60 THEN CAST(SUM(PGTO) AS MONEY) ELSE '' END AS 'SAFRA_60_PG'
	--,CASE
	--WHEN ATRASO_PGTO > 61			   THEN CAST(SUM(PGTO) AS MONEY) ELSE '' END AS 'SAFRA_90_PG'

INTO ##MAXQUERY2
FROM ##QUERY1
WHERE LOTE IS NOT NULL
GROUP BY LOTE,LOTEP,PGTO
ORDER BY LOTE ASC

SELECT
 LOTE
,MAX(SAFRA_30) AS 'SAFRA_30'
,MAX(SAFRA_60) AS 'SAFRA_60'
,MAX(SAFRA_90) AS 'SAFRA_90'
--,MAX(SAFRA_30_PG) AS 'SAFRA_30_PG'
--,MAX(SAFRA_60_PG) AS 'SAFRA_60_PG'
--,MAX(SAFRA_90_PG) AS 'SAFRA_90_PG'

FROM ##MAXQUERY2
GROUP BY LOTE
ORDER BY LOTE ASC




SELECT 
LOTE
,CASE
	WHEN ATRASO_PGTO BETWEEN 5 AND 30	THEN CAST(SUM(PGTO) AS MONEY) ELSE '' END AS 'SAFRA 30 PGTO'
	,CASE
	WHEN ATRASO_PGTO BETWEEN 31 AND 60	THEN CAST(SUM(PGTO) AS MONEY) ELSE '' END AS 'SAFRA 60 PGTO'
	,CASE
	WHEN ATRASO_PGTO > 61				THEN CAST(SUM(PGTO) AS MONEY) ELSE '' END AS 'SAFRA 90 PGTO'

,VLR_PGTO

INTO ##MAXQUERY3
FROM ##QUERY1
WHERE LOTE IS NOT NULL
GROUP BY LOTE,DATA_PGTO
,CASE
	WHEN ATRASO_PGTO BETWEEN 5 AND 30	THEN CAST(SUM(PGTO) AS MONEY) ELSE '' END 
	,CASE
	WHEN ATRASO_PGTO BETWEEN 31 AND 60	THEN CAST(SUM(PGTO) AS MONEY) ELSE '' END
	,CASE
	WHEN ATRASO_PGTO > 61				THEN CAST(SUM(PGTO) AS MONEY) ELSE '' END
ORDER BY LOTE ASC




SELECT
 LOTE
,MAX([SAFRA 30 PGTO]) AS 'SAFRA 30 PGTO'
,MAX([SAFRA 60 PGTO]) AS 'SAFRA 60 PGTO'
,MAX([SAFRA 90 PGTO]) AS 'SAFRA 90 PGTO'

FROM ##MAXQUERY3
GROUP BY LOTE
ORDER BY LOTE ASC




SELECT
 DATA_ENTRADA
,CONTRATO
,LOTE
,LOTEP
,PGTO
,DATA_PGTO
,CAST(ATRASO_PGTO AS INT)
FROM ##QUERY1