IF OBJECT_ID('tempdb..##CARGA_DIA_FASE2_1') IS NOT NULL DROP TABLE ##CARGA_DIA_FASE2_1
IF OBJECT_ID('tempdb..##TELEFONES_FASE2_1') IS NOT NULL DROP TABLE ##TELEFONES_FASE2_1
IF OBJECT_ID('tempdb..##RAWOUT_FASE2_1') IS NOT NULL DROP TABLE ##RAWOUT_FASE2_1
/*==========================================================================EXTRAI CARGA DIA=============================================================================================================*/
SELECT DISTINCT
'AVON CYBER' AS CEDENTE,
V3.ID_CLIENTE AS EC,
NOME AS NOME,
CPF,
CLI.NU_CPF_CNPJ,
DEP.NM_DEPOSITO AS DEPOSITO,
MAX(CONVERT(VARCHAR, CLI.DT_NASCIMENTO, 103)) AS 'DATA NASC'
INTO ##CARGA_DIA_FASE2_1 FROM LOCALCOB_DW..CARTEIRA_AVON_V3_DIA V3
INNER JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].TB_CLIENTE CLI ON V3.CPF = CLI.NU_CPF_CNPJ
LEFT JOIN (
SELECT A.ID_CLIENTE, A.NM_CLIENTE_CEDENTE AS RA, B.ID_DEPOSITO, B.NM_DEPOSITO FROM [10.155.4.158].[EASYCOLLECTOR].[DBO].TB_CLIENTE A
LEFT JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].TB_DEPOSITO B ON A.ID_DEPOSITO = B.ID_DEPOSITO
) DEP  ON CLI.ID_CLIENTE = DEP.ID_CLIENTE

WHERE V3.IMPORT_cob = 506
AND V3.DATA_BASE = CONVERT(DATE, GETDATE(),103)
--AND V3.ATRASO BETWEEN 8 AND 30
AND V3.VL_SALDO > 18
AND V3.ACORDO_ATIVO = 'NÃO'
AND V3.DEPOSITO = 'FASE 2 - SEM DISCAGEM - 1081 A 1800'

GROUP BY
V3.ID_CLIENTE,
NOME,
CPF,
CLI.NU_CPF_CNPJ,
DEP.NM_DEPOSITO

/*==========================================================================EXTRAI E MODELA TELEFONES====================================================================================================*/
SELECT Distinct
CustomerID as EC,
DNIS As TELEFONE,
CASE
       WHEN LEN(DNIS) = 11 THEN 'CELULAR' ELSE 'FIXO' END AS TIPO_TEL,
MAX(Convert(Date, CallStart, 103)) as DATA_ACIONAMENTO
INTO ##TELEFONES_FASE2_1
FROM [ADCOBMIS01].[DBO].[AVON_CPC_PURO]  
Where CustomerID Is Not Null
Group By
CustomerID,
DNIS,
CASE
       WHEN LEN(DNIS) = 11 THEN 'CELULAR' ELSE 'FIXO' END

/*==========================================================================CPC DA BASE==================================================================================================================*/
IF OBJECT_ID('tempdb..##TUDOTEL_F2') IS NOT NULL DROP TABLE ##TUDOTEL_F2
CREATE TABLE ##TUDOTEL_F2 (
       EC BIGINT, 
       TELEFONE BIGINT,
       PRI VARCHAR(10)
)
CREATE UNIQUE CLUSTERED INDEX [IX_tmp_TUDOTEL] ON ##TUDOTEL_F2 (EC,TELEFONE);
 
/*tudotel*/
 
-- select * from ##TELEFONES 
/*cpc*/
insert into ##TUDOTEL_F2
SELECT distinct FORA.EC, FORA.TELEFONE, 'A' AS PRI  FROM (
SELECT DISTINCT
ROW_NUMBER()over(partition by    B.TELEFONE order by B.TELEFONE) As QUANTIDADE,
A.EC,
CAST(B.TELEFONE AS BIGINT) AS TELEFONE
FROM ##CARGA_DIA_FASE2_1 A
LEFT JOIN ##TELEFONES_FASE2_1 B ON A.EC = B.EC
WHERE B.TELEFONE IS NOT NULL
)FORA
left join  ##TUDOTEL_F2 FJTEM ON
FJTEM.EC=FORA.EC 
AND FJTEM.TELEFONE=FORA.TELEFONE
where
FJTEM.EC IS NULL
 
 
/*sem cpc*/ 
insert into ##TUDOTEL_F2
 
select
X.EC, 
X.TELEFONE,
MIN(X.PRI)
from
(SELECT FORA.EC, FORA.TELEFONE, 'B'+[ADCOBMIS01].dbo.strzero(FORA.QUANTIDADE,3) AS PRI FROM (
SELECT 
A.EC,
CAST(CAST(C.NU_DDD AS VARCHAR)+CAST(C.NU_TELEFONE AS VARCHAR) AS BIGINT) AS TELEFONE,
ROW_NUMBER()over(partition by   A.EC order by C.TP_PREFERENCIAL DESC, C.TP_HABILITADO, C.TP_ORIGEM desc) As QUANTIDADE
FROM ##CARGA_DIA_FASE2_1 A
INNER JOIN [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_CLIENTE_TELEFONE] C ON A.EC = C.ID_CLIENTE
left join  ##TUDOTEL_F2 FJTEM ON
FJTEM.EC=A.EC 
AND FJTEM.TELEFONE=CAST(CAST(C.NU_DDD AS VARCHAR)+CAST(C.NU_TELEFONE AS VARCHAR) AS BIGINT)
where
FJTEM.EC IS NULL

--select * from [10.155.4.158].[EASYCOLLECTOR].[DBO].[TB_CLIENTE_TELEFONE] WHERE ID_CLIENTE = 732022
 
-- group by A.EC, CAST(CAST(C.NU_DDD AS VARCHAR)+CAST(C.NU_TELEFONE AS VARCHAR) AS BIGINT),C.TP_PREFERENCIAL, C.TP_ORIGEM
-- ORDER BY C.TP_PREFERENCIAL, C.TP_ORIGEM desc
)FORA ) X
 
group by X.EC, X.TELEFONE


/*===========================================================*/
 
 IF OBJECT_ID('tempdb..##DESCONHECE_F2') IS NOT NULL DROP TABLE ##DESCONHECE_F2

SELECT * 
INTO ##DESCONHECE_F2 
FROM (

SELECT
A.COD_EVENTO,
A.TELEFONE2,
COUNT(A.TELEFONE2) AS REPETICAO_DESC

FROM ADCOBMIS01..AVON_DADOS_DISCAGEM_PBI A 
WHERE A.COD_EVENTO = 331
AND A.DATA_BD BETWEEN CONVERT(DATE, GETDATE()-90, 103) AND CONVERT(DATE, GETDATE(), 103)  

GROUP BY 
COD_EVENTO,
TELEFONE2
) DESCO
WHERE DESCO.REPETICAO_DESC >=3

 
IF OBJECT_ID('tempdb..##ESTRAIR_DESC_F2') IS NOT NULL DROP TABLE ##ESTRAIR_DESC_F2
SELECT* into ##ESTRAIR_DESC_F2 FROM ##TUDOTEL_F2 A
 INNER JOIN ##DESCONHECE_F2 B ON A.TELEFONE = B.TELEFONE2

/*EXPORTA CLIENTES DESCONHECIDOS*/
DECLARE @BCPSQL_EXT VARCHAR(2000),
@BCPFILENAME_EXT VARCHAR(200)
SET @BCPFILENAME_EXT = '\\10.155.4.51\itf_in\AVON\DESCONHECE_CLIENTE\DESC_CLI_M0_AVON'+'_'+REPLACE((CONVERT(VARCHAR,CONVERT(DATE,(GETDATE())))),'-','')+'.CSV'
SET @BCPSQL_EXT = 'SELECT * FROM ##ESTRAIR_DESC_F2'
SET @BCPSQL_EXT = 'BCP "' + @BCPSQL_EXT + '" QUERYOUT ' + @BCPFILENAME_EXT + ' -c -t; -r\n -CP850 -T -Slocalhost'
PRINT @BCPSQL_EXT 
 
DECLARE @RC_EXT VARCHAR(100)
EXEC @RC_EXT = MASTER..XP_CMDSHELL @BCPSQL_EXT
 /*=======================================================================*/

DELETE A FROM ##TUDOTEL_F2 A
 INNER JOIN ##DESCONHECE_F2 B ON A.TELEFONE = B.TELEFONE2
---- )TUDOTEL
--select * from ##TUDOTEL 
--where ec = 732022
--order by 1, 3 asc
 
/*ORDENA OS TELEFONES*/
IF OBJECT_ID('tempdb..##RAW1_F2') IS NOT NULL DROP TABLE ##RAW1_F2
SELECT 
EC
,PRI
, CASE WHEN ROW_NUMBER()over(partition by EC order by EC,PRI)= 1 THEN TELEFONE END AS TEL1
, CASE WHEN ROW_NUMBER()over(partition by EC order by EC,PRI)= 2 THEN TELEFONE END AS TEL2
, CASE WHEN ROW_NUMBER()over(partition by EC order by EC,PRI)= 3 THEN TELEFONE END AS TEL3
, CASE WHEN ROW_NUMBER()over(partition by EC order by EC,PRI)= 4 THEN TELEFONE END AS TEL4
, CASE WHEN ROW_NUMBER()over(partition by EC order by EC,PRI)= 5 THEN TELEFONE END AS TEL5
, CASE WHEN ROW_NUMBER()over(partition by EC order by EC,PRI)= 6 THEN TELEFONE END AS TEL6
, CASE WHEN ROW_NUMBER()over(partition by EC order by EC,PRI)= 7 THEN TELEFONE END AS TEL7
, CASE WHEN ROW_NUMBER()over(partition by EC order by EC,PRI)= 8 THEN TELEFONE END AS TEL8
, CASE WHEN ROW_NUMBER()over(partition by EC order by EC,PRI)= 9 THEN TELEFONE END AS TEL9
, CASE WHEN ROW_NUMBER()over(partition by EC order by EC,PRI)= 10      THEN TELEFONE END AS TEL10
INTO ##RAW1_F2
FROM ##TUDOTEL_F2
ORDER BY PRI ASC
IF OBJECT_ID('tempdb..##RAW2_F2') IS NOT NULL DROP TABLE ##RAW2_F2
SELECT

MAX(A.TEL1) AS TEL1
,MAX(A.TEL2) AS TEL2
,MAX(A.TEL3) AS TEL3
,MAX(A.TEL4) AS TEL4
,MAX(A.TEL5) AS TEL5
,MAX(A.TEL6) AS TEL6
,MAX(A.TEL7) AS TEL7
,MAX(A.TEL8) AS TEL8
,MAX(A.TEL9) AS TEL9
,MAX(A.TEL10) AS TEL10
,B.CEDENTE
,A.EC
,B.NOME
,B.CPF
,B.[DATA NASC]
,B.DEPOSITO
INTO ##RAW2_F2
FROM ##RAW1_F2 A
INNER JOIN ##CARGA_DIA_FASE2_1 B ON A.EC = B.EC
GROUP BY
-- A.PRI,
B.CEDENTE,
A.EC,
B.NOME,
B.CPF,
B.[DATA NASC],
B.DEPOSITO
-- ORDER BY A.PRI ASC
 
IF OBJECT_ID('tempdb..##RAWOUT_F2') IS NOT NULL DROP TABLE ##RAWOUT_F2
SELECT
CASE WHEN LEFT(TEL1,2) IS NULL THEN '' ELSE LEFT(TEL1,2) END AS DDD1,
CASE WHEN (CASE WHEN LEN(TEL1) = 11 THEN RIGHT(TEL1,9) ELSE RIGHT(TEL1,8) END) IS NULL THEN '' ELSE (CASE WHEN LEN(TEL1) = 11 THEN RIGHT(TEL1,9) ELSE RIGHT(TEL1,8) END) END AS TEL1,
CASE WHEN LEFT(TEL2,2) IS NULL THEN '' ELSE LEFT(TEL2,2) END AS DDD2,
CASE WHEN (CASE WHEN LEN(TEL2) = 11 THEN RIGHT(TEL2,9) ELSE RIGHT(TEL2,8) END) IS NULL THEN '' ELSE (CASE WHEN LEN(TEL2) = 11 THEN RIGHT(TEL2,9) ELSE RIGHT(TEL2,8) END) END AS TEL2,
CASE WHEN LEFT(TEL3,2) IS NULL THEN '' ELSE LEFT(TEL3,2) END AS DDD3,
CASE WHEN (CASE WHEN LEN(TEL3) = 11 THEN RIGHT(TEL3,9) ELSE RIGHT(TEL3,8) END) IS NULL THEN '' ELSE (CASE WHEN LEN(TEL3) = 11 THEN RIGHT(TEL3,9) ELSE RIGHT(TEL3,8) END) END AS TEL3,
CASE WHEN LEFT(TEL4,2) IS NULL THEN '' ELSE LEFT(TEL4,2) END AS DDD4,
CASE WHEN (CASE WHEN LEN(TEL4) = 11 THEN RIGHT(TEL4,9) ELSE RIGHT(TEL4,8) END) IS NULL THEN '' ELSE (CASE WHEN LEN(TEL4) = 11 THEN RIGHT(TEL4,9) ELSE RIGHT(TEL4,8) END) END AS TEL4,
CASE WHEN LEFT(TEL5,2) IS NULL THEN '' ELSE LEFT(TEL5,2) END AS DDD5,
CASE WHEN (CASE WHEN LEN(TEL5) = 11 THEN RIGHT(TEL5,9) ELSE RIGHT(TEL5,8) END) IS NULL THEN '' ELSE  (CASE WHEN LEN(TEL5) = 11 THEN RIGHT(TEL5,9) ELSE RIGHT(TEL5,8) END) END AS TEL5,
CASE WHEN LEFT(TEL6,2) IS NULL THEN '' ELSE LEFT(TEL6,2) END AS DDD6,
CASE WHEN (CASE WHEN LEN(TEL6) = 11 THEN RIGHT(TEL6,9) ELSE RIGHT(TEL6,8) END) IS NULL THEN '' ELSE (CASE WHEN LEN(TEL6) = 11 THEN RIGHT(TEL6,9) ELSE RIGHT(TEL6,8) END) END AS TEL6,
CASE WHEN LEFT(TEL7,2) IS NULL THEN '' ELSE LEFT(TEL7,2) END AS DDD7,
CASE WHEN (CASE WHEN LEN(TEL7) = 11 THEN RIGHT(TEL7,9) ELSE RIGHT(TEL7,8) END) IS NULL THEN '' ELSE (CASE WHEN LEN(TEL7) = 11 THEN RIGHT(TEL7,9) ELSE RIGHT(TEL7,8) END) END AS TEL7,
CASE WHEN LEFT(TEL8,2) IS NULL THEN '' ELSE LEFT(TEL8,2) END AS DDD8,
CASE WHEN (CASE WHEN LEN(TEL8) = 11 THEN RIGHT(TEL8,9) ELSE RIGHT(TEL8,8) END) IS NULL THEN '' ELSE (CASE WHEN LEN(TEL8) = 11 THEN RIGHT(TEL8,9) ELSE RIGHT(TEL8,8) END) END AS TEL8,
CASE WHEN LEFT(TEL9,2) IS NULL THEN '' ELSE LEFT(TEL9,2) END AS DDD9,
CASE WHEN  (CASE WHEN LEN(TEL9) = 11 THEN RIGHT(TEL9,9) ELSE RIGHT(TEL9,8) END) IS NULL THEN '' ELSE (CASE WHEN LEN(TEL9) = 11 THEN RIGHT(TEL9,9) ELSE RIGHT(TEL9,8) END) END AS TEL9,
CASE WHEN LEFT(TEL10,2) IS NULL THEN '' ELSE LEFT(TEL10,2) END AS DDD10,
CASE WHEN (CASE WHEN LEN(TEL10) = 11 THEN RIGHT(TEL10,9) ELSE RIGHT(TEL10,8) END) IS NULL THEN '' ELSE (CASE WHEN LEN(TEL10) = 11 THEN RIGHT(TEL10,9) ELSE RIGHT(TEL10,8) END) END AS TEL10,
CEDENTE,
EC,
NOME,
CPF,
[DATA NASC]
INTO ##RAWOUT_F2
FROM ##RAW2_F2

SELECT * FROM ##RAWOUT_F2


 
--DECLARE @BCPSQL_SMS VARCHAR(2000),
--@BCPFILENAME_SMS VARCHAR(200)
--SET @BCPFILENAME_SMS = '\\10.155.4.51\itf_in\AVON\ARQUIVOS_RAW\AVON_FASE_2_HIGIENIZACAO_OLOS_ENVIO'+'_'+REPLACE((CONVERT(VARCHAR,CONVERT(DATE,(GETDATE())))),'-','')+'.txt'
--SET @BCPSQL_SMS = 'SELECT * FROM ##RAWOUT_F2'
--SET @BCPSQL_SMS = 'BCP "' + @BCPSQL_SMS + '" QUERYOUT ' + @BCPFILENAME_SMS + ' -c -t; -r\n -CP850 -T -Slocalhost'
--PRINT @BCPSQL_SMS 
 
--DECLARE @RC_SMS VARCHAR(100)
--EXEC @RC_SMS = MASTER..XP_CMDSHELL @BCPSQL_SMS
 
