IF OBJECT_ID('tempdb..##BASEKROTON') IS NOT NULL DROP TABLE ##BASEKROTON
SELECT DISTINCT

 A.NUMCONTRDIV
,CONVERT(DATE, A.DATCHEGBODERDIV) AS DATA_ENTRADA
,CASE                   WHEN A.CODEMPRESA = 53008 AND CODPRODCONTRDIV = 'AEDU'                THEN 'Anhanguera EAD'
                        WHEN A.CODEMPRESA = 53008 AND CODPRODCONTRDIV = 'EAD'                 THEN 'Unopar'
                        WHEN A.CODEMPRESA = 53011                                             THEN 'Anhanguera Campus'
                        WHEN A.CODEMPRESA = 53013                                             THEN 'Olimpo'
                        WHEN A.CODEMPRESA = 53009                                             THEN 'Pós EAD'
                        WHEN A.CODEMPRESA = 53010                                             THEN 'Pós Presencial'
                        END                                                                     EMPRESA

,CASE					WHEN A.CODEMPRESA = 53008 AND CODPRODCONTRDIV = 'AEDU'				  THEN 'EAD'
                        WHEN A.CODEMPRESA = 53008 AND CODPRODCONTRDIV = 'EAD'				  THEN 'EAD'
                        WHEN A.CODEMPRESA = 53011                                             THEN 'PRESENCIAL'
                        WHEN A.CODEMPRESA = 53013                                             THEN 'PRESENCIAL'
                        WHEN A.CODEMPRESA = 53009                                             THEN 'PRESENCIAL'
                        WHEN A.CODEMPRESA = 53010                                             THEN 'PRESENCIAL'
                        END       MODALIDADE


,CASE					WHEN A.CODEMPRESA = 53008 AND CODPRODCONTRDIV = 'AEDU'				  THEN 'AESA'
                        WHEN A.CODEMPRESA = 53008 AND CODPRODCONTRDIV = 'EAD'				  THEN 'DM'
                        WHEN A.CODEMPRESA = 53011                                             THEN 'AESA'
                        WHEN A.CODEMPRESA = 53013                                             THEN 'DM'
                        WHEN A.CODEMPRESA = 53009                                             THEN 'DM'
                        WHEN A.CODEMPRESA = 53010                                             THEN 'DM'
                        END       MARCA

,A.CODCPFCNPJCLI AS CPF_CLIENTE
,CAST(A.SALDOATRASO AS MONEY) AS SALDO
,A.FAIXAATRASO AS ATRASO
,CASE 
      WHEN A.SALDOATRASO BETWEEN 0 AND 100 THEN 'Até 100,00'  
      WHEN A.SALDOATRASO BETWEEN 100.1 AND 500 THEN '100,01 A 500,00'
      WHEN A.SALDOATRASO BETWEEN 500.1 AND 1000 THEN '500,01 A 1.000,00'
      WHEN A.SALDOATRASO BETWEEN 1000.1 AND 1500 THEN '1.000,01 A 1.500,00'
      WHEN A.SALDOATRASO BETWEEN 1500.1 AND 2500 THEN '1.500,01 A 2.500,00'
      WHEN A.SALDOATRASO BETWEEN 2500.1 AND 5000 THEN '2.500,01 A 5.000,00'
      WHEN A.SALDOATRASO BETWEEN 5000.1 AND 10000 THEN '5.000,01 A 10.000,00'
      WHEN A.SALDOATRASO >10000 THEN 'Acima de 10.000,00'
      END FAIXA_VALOR
                        
,CASE
	WHEN A.SALDOATRASO BETWEEN	1	 and	30		THEN	'1 - 1 a 30'
	 WHEN A.SALDOATRASO BETWEEN	31	 and	60		THEN	'2 - 31 a 60'
	 WHEN A.SALDOATRASO BETWEEN	61	 and	90		THEN	'3 - 61 a 90'
	 WHEN A.SALDOATRASO BETWEEN	91	 and	120		THEN	'4 - 91 a 120'
	 WHEN A.SALDOATRASO BETWEEN	121	 and	121		THEN	'5 - 121 a 121'
	 WHEN A.SALDOATRASO BETWEEN	151	 and	180		THEN	'6 - 151 a 180'
	 WHEN A.SALDOATRASO BETWEEN	181	 and	210		THEN	'7 - 181 a 210'
	 WHEN A.SALDOATRASO BETWEEN	211	 and	240		THEN	'8 - 211 a 240'
	 WHEN A.SALDOATRASO BETWEEN	241	 and	271		THEN	'9 - 241 a 271'
	 WHEN A.SALDOATRASO BETWEEN	271	 and	300		THEN	'10 - 271 a 300'
	 WHEN A.SALDOATRASO BETWEEN	301	 and	330		THEN	'11 - 301 a 330'
	 WHEN A.SALDOATRASO BETWEEN	331	 and	360		THEN	'12 - 331 a 360'
	 WHEN A.SALDOATRASO BETWEEN	361	 and	540		THEN	'13 - 361 a 540'
	 WHEN A.SALDOATRASO BETWEEN	541	 and	720		THEN	'14 - 541 a 720'
	 WHEN A.SALDOATRASO BETWEEN	721	 and	900		THEN	'15 - 721 a 900'
	 WHEN A.SALDOATRASO BETWEEN	901	 and	1080	THEN	'16 - 901 a 1080'
	 WHEN A.SALDOATRASO BETWEEN	1081 and	1440	THEN	'17 - 1081 a 1440'
	 WHEN A.SALDOATRASO BETWEEN	1441 and	1800	THEN	'18 - 1441 a 1800'
	 WHEN A.SALDOATRASO BETWEEN	1801 and	2160	THEN	'19 - 1801 a 2160'
		WHEN A.SALDOATRASO >	2161				THEN    '20 - 2161 Ou Mais'
	  END FAIXA_ATRASO
	  
	  ,CONVERT(DATE,GETDATE()) AS DATA
INTO ##BASEKROTON
FROM ADCOBDAT..AU100 A With (Nolock)
WHERE A.CODEMPRESA IN (53008, 53009, 53010, 53011, 53013)


/*-------------EXTRAI AS TENTATIVAS--------------*/
IF OBJECT_ID('tempdb..##TENTATIVAS') IS NOT NULL DROP TABLE ##TENTATIVAS
SELECT
BASE.MARCA,
BASE.MODALIDADE,
BASE.FAIXA_ATRASO,
COUNT(BASE.FAIXA_ATRASO) AS SPIN
INTO ##TENTATIVAS
FROM ADCOBDAT..CO030 TENT
INNER JOIN ##BASEKROTON BASE ON BASE.NUMCONTRDIV = TENT.NUMCONTRDIV
WHERE CODEMPRESA IN (53008, 53009, 53010, 53011, 53013)
AND CONVERT(DATE,DATHISTCOB, 103) BETWEEN '2020-06-01' AND CONVERT(DATE, GETDATE(), 103)
AND BASE.FAIXA_ATRASO IS NOT NULL
GROUP BY 
BASE.MARCA,
BASE.MODALIDADE,
BASE.FAIXA_ATRASO


/*-------------ANALITICO DE CARGA SOMADO--------------*/

SELECT
A.MARCA,
A.MODALIDADE,
'LOCALCRED' AS ESCOB,
COUNT(A.FAIXA_ATRASO) AS Quantidade,
SUM(A.SALDO) AS Saldo,
A.FAIXA_ATRASO AS Aging,
B.SPIN,
A.[DATA]
FROM ##BASEKROTON A
INNER JOIN ##TENTATIVAS B ON A.MARCA = B.MARCA AND A.MODALIDADE = B.MODALIDADE AND A.FAIXA_ATRASO = B.FAIXA_ATRASO
WHERE A.FAIXA_ATRASO IS NOT NULL
GROUP BY 
A.MARCA,
A.MODALIDADE,
A.FAIXA_ATRASO,
B.SPIN,
A.[DATA]

ORDER BY MARCA ASC


--DECLARE @BCPSQL_SMS VARCHAR(2000),
--@BCPFILENAME_SMS VARCHAR(200)
--SET @BCPFILENAME_SMS = '\\10.155.4.51\itf_in\BMW\SMS\SMS_BMW'+'_'+REPLACE((CONVERT(VARCHAR,CONVERT(DATE,(GETDATE())))),'-','')+'.txt'
--SET @BCPSQL_SMS = 'SELECT NUMCONTRDIV,NUMTELCELCLI,LAYOUT_A FROM ##SMS_BMW'
--SET @BCPSQL_SMS = 'BCP "' + @BCPSQL_SMS + '" QUERYOUT ' + @BCPFILENAME_SMS + ' -c -t; -r\n -CP850 -T -Slocalhost'
--PRINT @BCPSQL_SMS 
 
--DECLARE @RC_SMS VARCHAR(100)
--EXEC @RC_SMS = MASTER..XP_CMDSHELL @BCPSQL_SMS
 