IF OBJECT_ID('tempdb..##8A30') IS NOT NULL DROP TABLE ##8A30
IF OBJECT_ID('tempdb..##31A60') IS NOT NULL DROP TABLE ##31A60
IF OBJECT_ID('tempdb..##61A90') IS NOT NULL DROP TABLE ##61A90

SELECT TOP 100 * INTO ##8A30 FROM LOCALCOB_DW..CARTEIRA_AVON_V3_DIA
WHERE IMPORT_cob = 002
AND ATRASO BETWEEN 8 AND 30
order by VL_SALDO DESC

SELECT TOP 100 * INTO ##31A60 FROM LOCALCOB_DW..CARTEIRA_AVON_V3_DIA
WHERE IMPORT_cob = 002
AND ATRASO BETWEEN 31 AND 60
order by VL_SALDO DESC

SELECT TOP 100 * INTO ##61A90 FROM LOCALCOB_DW..CARTEIRA_AVON_V3_DIA
WHERE IMPORT_cob = 002
AND ATRASO BETWEEN 61 AND 90
order by VL_SALDO DESC

IF OBJECT_ID('tempdb..##UNION86090') IS NOT NULL DROP TABLE ##UNION86090

SELECT * INTO ##UNION86090 FROM (
SELECT * FROM ##8A30
UNION ALL
SELECT * FROM ##31A60
UNION ALL
SELECT * FROM ##61A90
) A

IF OBJECT_ID('tempdb..##FINAL') IS NOT NULL DROP TABLE ##FINAL
SELECT 

CAST(DATA_BASE AS VARCHAR) AS DATA_BASE,
CAST(ID_CLIENTE AS VARCHAR) AS ID_CLIENTE,
CAST(RA AS VARCHAR) AS RA,
CAST(NOME AS VARCHAR) AS NOME,
CAST(CPF AS VARCHAR) AS CPF,
CAST(SEXO AS VARCHAR) AS SEXO,
CAST(ID_CONTRATO AS VARCHAR) AS ID_CONTRATO,
CAST(CONTRATO AS VARCHAR) AS CONTRATO,
CAST(CAMPANHA AS VARCHAR) AS CAMPANHA,
CAST(ANO_CAMPANHA AS VARCHAR) AS ANO_CAMPANHA,
CAST(UF AS VARCHAR) AS UF,
CAST(DT_VENCIMENTO AS VARCHAR) AS DT_VENCIMENTO,
CAST(ATRASO AS VARCHAR) AS ATRASO,
CAST(DT_INCLUSAO AS VARCHAR) AS DT_INCLUSAO,
CAST(ID_DIVIDA AS VARCHAR) AS ID_DIVIDA,
CAST(VL_SALDO AS VARCHAR) AS VL_SALDO,
CAST(FAIXA_ATRASO AS VARCHAR) AS FAIXA_ATRASO,
CAST(LOA AS VARCHAR) AS LOA,
CAST(SETOR AS VARCHAR) AS SETOR,
CAST(QUINTIL AS VARCHAR) AS QUINTIL,
CAST(FASE_COB AS VARCHAR) AS FASE_COB,
CAST(RISCO_COB AS VARCHAR) AS RISCO_COB,
CAST(IMPORT_cob AS VARCHAR) AS IMPORT_cob,
CAST(ACORDO_ATIVO AS VARCHAR) AS ACORDO_ATIVO,
CAST(DT_ACORDO AS VARCHAR) AS DT_ACORDO,
CAST(DEPOSITO AS VARCHAR) AS DEPOSITO,
CAST(CONT_CONTRATOS AS VARCHAR) AS CONT_CONTRATOS

INTO ##FINAL
FROM ##UNION86090

INSERT INTO ##FINAL
SELECT 
'DATA_BASE'		AS 	DATA_BASE,
'ID_CLIENTE'	AS 	ID_CLIENTE,
'RA'			AS 	RA,
'NOME'			AS 	NOME,
'CPF'			AS 	CPF,
'SEXO'			AS 	SEXO,
'ID_CONTRATO'	AS 	ID_CONTRATO,
'CONTRATO'		AS 	CONTRATO,
'CAMPANHA'		AS 	CAMPANHA,
'ANO_CAMPANHA'	AS 	ANO_CAMPANHA,
'UF'			AS 	UF,
'DT_VENCIMENTO'	AS 	DT_VENCIMENTO,
'ATRASO'		AS 	ATRASO,
'DT_INCLUSAO'	AS 	DT_INCLUSAO,
'ID_DIVIDA'		AS 	ID_DIVIDA,	
'VL_SALDO'		AS 	VL_SALDO,
'FAIXA_ATRASO'	AS 	FAIXA_ATRASO,
'LOA'			AS 	LOA,
'SETOR'			AS 	SETOR,
'QUINTIL'		AS 	QUINTIL,
'FASE_COB'		AS 	FASE_COB,
'RISCO_COB'		AS 	RISCO_COB,
'IMPORT_cob'	AS 	IMPORT_cob,
'ACORDO_ATIVO'	AS 	ACORDO_ATIVO,
'DT_ACORDO'		AS 	DT_ACORDO,
'DEPOSITO'		AS 	DEPOSITO,
'CONT_CONTRATOS'AS 	CONT_CONTRATOS	


DECLARE @BCPSQL_SMS VARCHAR(2000),
@BCPFILENAME_SMS VARCHAR(200)
SET @BCPFILENAME_SMS = '\\10.155.4.51\itf_in\AVON\MAIORES_CASOS\AVON_F1_TOP300_08A30_31A60_61A90'+'_'+REPLACE((CONVERT(VARCHAR,CONVERT(DATE,(GETDATE())))),'-','')+'.txt'
SET @BCPSQL_SMS = 'SELECT * FROM ##FINAL ORDER BY 1 DESC'
SET @BCPSQL_SMS = 'BCP "' + @BCPSQL_SMS + '" QUERYOUT ' + @BCPFILENAME_SMS + ' -c -t; -r\n -CP850 -T -Slocalhost'
PRINT @BCPSQL_SMS 
 
DECLARE @RC_SMS VARCHAR(100)
EXEC @RC_SMS = MASTER..XP_CMDSHELL @BCPSQL_SMS 
